"""``sp.paper_tables()`` — AER/QJE/Econometrica-style multi-panel paper tables.

Given a list of fitted results + a template name, produce the
standard multi-panel layout that top economics journals expect:

- **Main** — headline result across specifications (baseline →
  +covariates → +FE → +cluster).
- **Heterogeneity** — same outcome, subsamples / interactions.
- **Robustness** — alternative estimators on the same data.
- **Placebo** — outcomes that should NOT respond.

This is not a replacement for ``sp.regtable``; it is a convention
layer that enforces journal-specific presentation rules (three-line
rules, FE indicators, cluster notes, stars at (0.10, 0.05, 0.01)) so
the authors can hand off a LaTeX file to a co-author or journal
with no further formatting work.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Sequence

from .regression_table import regtable, RegtableResult


# ---------------------------------------------------------------------------
# Journal templates
# ---------------------------------------------------------------------------

TEMPLATES = {
    'aer': {
        'label': 'AER style',
        'star_levels': (0.10, 0.05, 0.01),
        'se_type': 'se',
        'stats': ('N', 'R-squared'),
        'notes_default': [
            "Standard errors in parentheses.",
            "*** p<0.01, ** p<0.05, * p<0.10.",
        ],
    },
    'qje': {
        'label': 'QJE style',
        'star_levels': (0.10, 0.05, 0.01),
        'se_type': 'se',
        'stats': ('N',),
        'notes_default': [
            "Robust standard errors in parentheses.",
            "*** p<0.01, ** p<0.05, * p<0.10.",
        ],
    },
    'econometrica': {
        'label': 'Econometrica style',
        'star_levels': (0.01, 0.05),     # only 5% and 1%
        'se_type': 'se',
        'stats': ('N', 'R-squared'),
        'notes_default': [
            "Standard errors in parentheses.",
            "** p<0.05, *** p<0.01.",
        ],
    },
    'restat': {
        'label': 'Review of Economics and Statistics style',
        'star_levels': (0.10, 0.05, 0.01),
        'se_type': 'se',
        'stats': ('N', 'R-squared'),
        'notes_default': [
            "Standard errors in parentheses.",
            "*** p<0.01, ** p<0.05, * p<0.10.",
        ],
    },
}


# ---------------------------------------------------------------------------
# Result container
# ---------------------------------------------------------------------------

@dataclass
class PaperTables:
    """Container for the multi-panel paper-table bundle.

    Each attribute is a RegtableResult (has .text, .latex, .html,
    .to_latex(), ...).  Iterate via ``.panels()`` or access by name:
    ``pt.main`` / ``pt.heterogeneity`` / ``pt.robustness`` / ``pt.placebo``.
    """
    main: Optional[RegtableResult] = None
    heterogeneity: Optional[RegtableResult] = None
    robustness: Optional[RegtableResult] = None
    placebo: Optional[RegtableResult] = None
    template: str = 'aer'

    def panels(self) -> Dict[str, RegtableResult]:
        """Return {name: RegtableResult} for every populated panel."""
        return {
            name: getattr(self, name)
            for name in ('main', 'heterogeneity', 'robustness', 'placebo')
            if getattr(self, name) is not None
        }

    def to_latex(self, path: Optional[str] = None) -> str:
        """Concatenate every panel's LaTeX into a single file.

        If ``path`` is provided, also write to disk.
        """
        parts: List[str] = []
        parts.append(
            f"% Tables generated by sp.paper_tables(template='{self.template}')"
        )
        parts.append("% Each table is self-contained; "
                     "include in your manuscript directly.")
        parts.append("")
        for name, tbl in self.panels().items():
            parts.append(f"% ========== Table: {name.upper()} ==========")
            parts.append(tbl.to_latex())
            parts.append("")
        content = "\n".join(parts)
        if path is not None:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(content)
        return content

    def to_markdown(self, path: Optional[str] = None) -> str:
        """Return all panels stacked as GitHub-flavoured Markdown."""
        parts: List[str] = []
        for name, tbl in self.panels().items():
            parts.append(f"## Table: {name.title()}")
            parts.append("")
            parts.append(tbl.to_markdown())
            parts.append("")
        content = "\n".join(parts)
        if path is not None:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(content)
        return content

    def to_text(self) -> str:
        """Return all panels stacked as plain text (terminal-friendly)."""
        parts: List[str] = []
        for name, tbl in self.panels().items():
            parts.append(f"=== {name.upper()} ===")
            parts.append(tbl.to_text())
            parts.append("")
        return "\n".join(parts)

    def __repr__(self) -> str:
        names = list(self.panels().keys())
        return (f"<PaperTables template='{self.template}' "
                f"panels={names}>")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def paper_tables(
    main: Optional[Sequence] = None,
    heterogeneity: Optional[Sequence] = None,
    robustness: Optional[Sequence] = None,
    placebo: Optional[Sequence] = None,
    template: str = 'aer',
    coef_labels: Optional[Dict[str, str]] = None,
    model_labels_main: Optional[List[str]] = None,
    model_labels_heterogeneity: Optional[List[str]] = None,
    model_labels_robustness: Optional[List[str]] = None,
    model_labels_placebo: Optional[List[str]] = None,
    keep: Optional[Sequence[str]] = None,
    filename: Optional[str] = None,
    latex_filename: Optional[str] = None,
) -> PaperTables:
    """Generate a journal-style multi-panel table bundle.

    Parameters
    ----------
    main : sequence of results
        Primary-specification results (one column per spec).  Typical
        sequence: baseline → +controls → +fixed effects → +cluster SE.
    heterogeneity : sequence of results, optional
        Heterogeneity panel: same outcome on subsamples or interactions.
    robustness : sequence of results, optional
        Alternative estimators on the same spec (e.g., OLS / IV /
        matching / DML).
    placebo : sequence of results, optional
        Outcomes that should NOT respond; point estimates should be
        near zero and non-significant.
    template : str, default 'aer'
        One of ``'aer'``, ``'qje'``, ``'econometrica'``, ``'restat'``.
        Sets star thresholds, SE style, and footer notes.
    coef_labels : dict, optional
        Rename coefficients consistently across all panels.
    model_labels_* : list of str, optional
        Column labels per panel.
    keep : list of str, optional
        Variable-name whitelist (shown across all panels).
    filename : str, optional
        If provided, write the Markdown version to this path.
    latex_filename : str, optional
        If provided, write the concatenated LaTeX to this path.

    Returns
    -------
    PaperTables
        With ``.main`` / ``.heterogeneity`` / ``.robustness`` /
        ``.placebo`` attributes (each a RegtableResult), plus
        ``.to_latex()`` and ``.to_markdown()`` serialisers.

    Examples
    --------
    Minimum (main panel only)::

        pt = sp.paper_tables(
            main=[r_baseline, r_controls, r_fe, r_cluster],
            template='aer',
        )
        pt.to_latex('table1.tex')

    Full AER-style bundle::

        pt = sp.paper_tables(
            main=[r1, r2, r3, r4],
            heterogeneity=[r_male, r_female],
            robustness=[r_ols, r_iv, r_dml],
            placebo=[r_pre_treatment, r_unrelated],
            template='aer',
            coef_labels={'d': 'Treatment', 'x1': 'Age'},
            model_labels_main=['Baseline', '+X', '+FE', '+Cluster'],
        )
        pt.to_latex('tables.tex')

    """
    if template not in TEMPLATES:
        raise ValueError(
            f"Unknown template {template!r}; choose from {list(TEMPLATES)}")
    style = TEMPLATES[template]

    def _build(results, title, model_labels):
        if not results:
            return None
        # regtable ships journal-appropriate footer notes by default
        # ("Standard errors in parentheses; * p<0.10, ...").  Do NOT
        # duplicate via template notes — pass None so only regtable's
        # defaults appear.
        return regtable(
            *results,
            title=title,
            model_labels=model_labels,
            coef_labels=coef_labels,
            keep=keep,
            stats=list(style['stats']),
            star_levels=style['star_levels'],
            se_type=style['se_type'],
            stars=True,
            output='text',
            notes=None,
        )

    pt = PaperTables(
        main=_build(main, 'Main results', model_labels_main),
        heterogeneity=_build(heterogeneity, 'Heterogeneity',
                             model_labels_heterogeneity),
        robustness=_build(robustness, 'Robustness',
                          model_labels_robustness),
        placebo=_build(placebo, 'Placebo outcomes',
                       model_labels_placebo),
        template=template,
    )

    if filename is not None:
        pt.to_markdown(filename)
    if latex_filename is not None:
        pt.to_latex(latex_filename)
    return pt
