"""``sp.etwfe(family='poisson', fe='unit')`` against Stata ``jwdid``.

Reference: Stata 18, ``jwdid`` v2.201 / ``jwdid_estat`` v2.2 (Rios-Avila)
with ``method(ppmlhdfe)`` (``ppmlhdfe`` 2.3.0), on the bytes of
``_fixtures/etwfe_poisson_jwdid_hettype.csv`` (360 units x 8 years, cohorts
2004 / 2006 / never, 13% all-zero units, a categorical ``xcat`` and a
time-varying continuous ``xc``), generated by
``_fixtures/_generate_etwfe_poisson_jwdid_Stata.do``.  Thirteen
specifications: every ``hettype()``, ``never``, a categorical and a
continuous covariate, and their combinations.  For each the fixture holds
``estat simple`` on both scales, ``estat event, predict(xb)`` and, with the
categorical covariate, ``estat simple, predict(xb) over(xcat)``.

On this panel ``ppmlhdfe`` flags the 384 all-zero rows as separated, so
``jwdid`` averages over the remaining ``e(sample)`` and counts 312 clusters:
the matching StatsPAI call is ``separated='drop'``.  (On the 923k-row panel
of the replication in ``CHANGELOG.md`` ``ppmlhdfe`` does not flag them and
``separated='keep'``, the default, is the match.)

Tolerances: link-scale estimates and every SE are the same closed-form
quantities on both sides (PPML solved to ~1e-15 by both), held to 1e-9 /
1e-7 relative.  The response-scale point estimate comes from Stata
``margins`` with its own numerical derivatives and solver tolerance, held
to 1e-6 relative.  Response-scale SEs are a documented convention
difference (profiled unit effect vs. absorbed effects held fixed; see the
module docstring of ``statspai.did._etwfe_nonlinear``): the default
``response_se='profile'`` is not compared, and ``response_se='margins'``
reproduces ``margins`` and is held to 1e-6 relative (Stata differentiates
numerically; the largest gap on these fixtures is 7e-7).

``_fixtures/etwfe_poisson_jwdid_margins_Stata.json``
(``_generate_etwfe_poisson_jwdid_margins_Stata.do``) adds ``estat event`` /
``group`` / ``calendar`` / ``simple, over(xcat)`` on the response scale for
the default design, ``i.xcat`` and ``cluster(cl)`` with
``cl = mod(id + year, 7)`` -- clusters that nest neither units nor periods,
so the covariance of ``ppmlhdfe``'s ``_cons`` with the slopes enters.  Its
response-scale point estimates of small subgroups carry ``ppmlhdfe``'s
default solver tolerance (up to 1.1e-5 relative on one ``over()`` level),
held to 2e-5.
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import statspai as sp

_FIX = Path(__file__).resolve().parent / "_fixtures"

SPECS = {
    "default": {},
    "event": {"hettype": "event"},
    "cohort": {"hettype": "cohort"},
    "time": {"hettype": "time"},
    "twfe": {"hettype": "twfe"},
    "never": {"cgroup": "nevertreated"},
    "never_cohort": {"cgroup": "nevertreated", "hettype": "cohort"},
    "never_event": {"cgroup": "nevertreated", "hettype": "event"},
    "xcat": {"xvar": "xcat"},
    "xc": {"xvar": "xc"},
    "xcat_event": {"xvar": "xcat", "hettype": "event"},
    "xcat_never": {"xvar": "xcat", "cgroup": "nevertreated"},
    "xcat_xc": {"xvar": ["xcat", "xc"]},
}


@pytest.fixture(scope="module")
def ref():
    return json.loads(
        (_FIX / "etwfe_poisson_jwdid_Stata.json").read_text(encoding="utf-8")
    )


@pytest.fixture(scope="module")
def panel():
    df = pd.read_csv(_FIX / "etwfe_poisson_jwdid_hettype.csv")
    df["xcat"] = df["xcat"].astype("category")  # Stata i.xcat
    return df


def _fit(df, separated="drop", **kw):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return sp.etwfe(
            df,
            y="y",
            group="id",
            time="year",
            first_treat="g",
            family="poisson",
            fe="unit",
            scale="link",
            separated=separated,
            **kw,
        )


@pytest.mark.parametrize("name", list(SPECS))
def test_matches_jwdid(ref, panel, name):
    r = _fit(panel, **SPECS[name])
    R = ref[name]
    agg = r.model_info["aggregations"]
    assert r.n_obs == R["N"]
    assert agg["link"]["simple"]["att"] == pytest.approx(
        R["simple_link"]["b"][0], rel=1e-9, abs=1e-12
    )
    assert agg["link"]["simple"]["se"] == pytest.approx(
        R["simple_link"]["se"][0], rel=1e-7
    )
    assert agg["response"]["simple"]["att"] == pytest.approx(
        R["simple_response"]["b"][0], rel=1e-6
    )
    rm = _fit(panel, response_se="margins", **SPECS[name]).model_info
    assert rm["aggregations"]["response"]["simple"]["se"] == pytest.approx(
        R["simple_response"]["se"][0], rel=1e-6
    )
    # estat event lists every event time from the first on (the reference
    # period with b = se = 0 under never); line them up by position.
    ev = agg["link"]["event"].set_index("relative_time")
    first = int(ev.index.min())
    for k, (b, se) in enumerate(zip(R["event_link"]["b"], R["event_link"]["se"])):
        e = first + k
        if se == 0:
            assert e not in ev.index  # the omitted reference period
            continue
        assert ev.loc[e, "att"] == pytest.approx(b, rel=1e-9, abs=1e-12)
        assert ev.loc[e, "se"] == pytest.approx(se, rel=1e-7)
    if "over_link" in R:
        by = sp.etwfe_emfx(r, type="simple", scale="link", by_xvar=True).detail
        by = by.set_index("level")
        for lev, b, se in zip(
            sorted(by.index), R["over_link"]["b"], R["over_link"]["se"]
        ):
            assert by.loc[lev, "att"] == pytest.approx(b, rel=1e-9, abs=1e-12)
            assert by.loc[lev, "se"] == pytest.approx(se, rel=1e-7)


MARGINS_SPECS = {
    "default": {},
    "xcat": {"xvar": "xcat"},
    "cluster_mixed": {"cluster": "cl"},
}


@pytest.fixture(scope="module")
def ref_margins():
    return json.loads(
        (_FIX / "etwfe_poisson_jwdid_margins_Stata.json").read_text(encoding="utf-8")
    )


@pytest.mark.parametrize("name", list(MARGINS_SPECS))
def test_margins_response_scale_matches_jwdid_estat(ref_margins, panel, name):
    """Every response-scale aggregate of ``estat`` with
    ``response_se='margins'``; ``estat`` lists them in the order of the
    StatsPAI tables (event time, cohort, calendar period, xcat level)."""
    R = ref_margins[name]
    df = panel.assign(cl=(panel["id"] + panel["year"]) % 7)
    r = _fit(df, response_se="margins", **MARGINS_SPECS[name])
    agg = r.model_info["aggregations"]
    assert r.n_obs == R["N"]
    assert agg["link"]["simple"]["se"] == pytest.approx(
        R["simple_link"]["se"][0], rel=1e-7
    )
    assert agg["response"]["simple"]["att"] == pytest.approx(
        R["simple_response"]["b"][0], rel=1e-6
    )
    assert agg["response"]["simple"]["se"] == pytest.approx(
        R["simple_response"]["se"][0], rel=1e-6
    )
    for key, tab in [
        ("event_response", "event"),
        ("group_response", "group"),
        ("calendar_response", "calendar"),
    ]:
        t = agg["response"][tab]
        assert len(t) == len(R[key]["b"])
        np.testing.assert_allclose(t["att"], R[key]["b"], rtol=2e-5)
        np.testing.assert_allclose(t["se"], R[key]["se"], rtol=1e-6)
    if "over_response" in R:
        by = sp.etwfe_emfx(r, type="simple", scale="response", by_xvar=True).detail
        np.testing.assert_allclose(by["att"], R["over_response"]["b"], rtol=2e-5)
        np.testing.assert_allclose(by["se"], R["over_response"]["se"], rtol=1e-6)


def test_keep_vs_drop_separated(panel):
    """``'keep'`` weights every treated row, ``'drop'`` only the
    non-separated ones; the coefficients are the same fit, and the SEs of a
    cell differ only through the cluster count in ``G / (G - 1)``."""
    keep = _fit(panel, separated="keep")
    drop = _fit(panel, separated="drop")
    ck = keep.model_info["cells"].set_index(["cohort", "period"])
    cd = drop.model_info["cells"].set_index(["cohort", "period"])
    np.testing.assert_allclose(ck["coef"], cd["coef"], rtol=0, atol=1e-12)
    G, Gd = keep.model_info["n_clusters"], drop.model_info["n_clusters"]
    assert (G, Gd) == (360, 312)
    ratio = np.sqrt((G / (G - 1)) / (Gd / (Gd - 1)))
    np.testing.assert_allclose(ck["se"], cd["se"] * ratio, rtol=1e-12)
    assert (ck["n_treated"] >= cd["n_treated"]).all()
    assert keep.n_obs == len(panel) and drop.n_obs == len(panel) - 384


def test_hettype_restricts_the_parameters(panel):
    """The pooled designs share one coefficient across the cells named."""
    for het, key in [("event", "relative_time"), ("cohort", "cohort")]:
        cells = _fit(panel, hettype=het).model_info["cells"]
        post = cells[cells["post"]]
        spread = post.groupby(key)["coef"].agg(lambda c: c.max() - c.min())
        assert (spread < 1e-12).all()
        assert post.groupby(key)["param"].nunique().eq(1).all()
    tw = _fit(panel, hettype="twfe").model_info
    assert tw["treatment_params"] == ["treat[post]"]
    assert np.ptp(tw["cells"]["coef"].to_numpy()) < 1e-12


def test_by_xvar_needs_a_categorical_xvar(panel):
    from statspai.exceptions import MethodIncompatibility

    r = _fit(panel, xvar="xc")
    with pytest.raises(MethodIncompatibility, match="categorical"):
        sp.etwfe_emfx(r, type="simple", by_xvar=True)
    lin = sp.etwfe(panel, y="y", group="id", time="year", first_treat="g")
    with pytest.raises(MethodIncompatibility, match="by_xvar"):
        sp.etwfe_emfx(lin, type="simple", by_xvar=True)


def test_by_xvar_event_and_group_tables(panel):
    r = _fit(panel, xvar="xcat")
    ev = sp.etwfe_emfx(r, type="event", by_xvar=True).detail
    assert {"level", "relative_time", "att", "se"} <= set(ev.columns)
    assert set(ev["level"]) == set(panel["xcat"].cat.categories)
    grp = sp.etwfe_emfx(r, type="group", by_xvar=True).detail
    assert {"level", "cohort"} <= set(grp.columns)


def test_collinear_covariate_levels_are_omitted(panel):
    """A level absent from a cohort makes the others sum to one inside its
    cells; the dependent interaction is omitted (as ppmlhdfe does) and the
    fit still converges to the same aggregates the full-rank design gives
    once that level is merged away."""
    d = panel.copy()
    lev = d["xcat"].astype(int).to_numpy()
    lev[(d["g"] == 2006).to_numpy() & (lev == 1)] = 2  # no level 1 in 2006
    d["xcat"] = pd.Categorical(lev)
    with warnings.catch_warnings():
        warnings.simplefilter("error", RuntimeWarning)
        r = _fit(d, xvar="xcat")
    assert r.model_info["converged"]
    assert any(":xcat[" in o for o in r.model_info["omitted"])
    assert np.isfinite(r.estimate) and np.isfinite(r.se)
