"""Stata ``nprobust::lprobust`` parity for ``sp.lprobust_at_point``.

``lprobust`` is the engine ``did_had`` is built on — it computes the
counterfactual outcome evolution of a quasi-untreated group as the local
polynomial intercept at dose zero, and ``did_had`` reads four numbers off
its ``e(Result)``. Reproducing it exactly is a precondition for
reproducing ``did_had`` at all, so it is pinned here on its own, at
**supplied** bandwidths.

The estimator is tested first, at **supplied** bandwidths
(``TestLprobustParity``), so a failure there cannot be a bandwidth
difference. The *selectors* are then tested separately, each in its own
class. Keeping the two apart is what makes a mismatch localizable.

Golden numbers from Stata 18 MP, ``nprobust`` (installed from the
authors' repo), generated by
``tests/stata_parity/option_parity/86_lprobust.do`` over three kernels ×
three bandwidths, plus one case with ``b != h`` — the case that catches
whether the fit uses the union of the two bandwidth windows.

The selectors
-------------
Five of the six ``lprobust`` accepts are ported and pinned against **R**
``nprobust`` (which reports both ``h`` and ``b``, where Stata's ``rho=1``
hides ``b``), cross-checked against Stata's ``h``:

===========  ==============================  ========  ==========
bwselect     sp. function                    vs R      vs Stata
===========  ==============================  ========  ==========
``mse-dpi``  :func:`sp.lpbwselect_mse_dpi`   5.6e-13   2.4e-9
``mse-rot``  :func:`sp.lpbwselect_mse_rot`   4.3e-12   5.1e-8
``imse-dpi`` :func:`sp.lpbwselect_imse_dpi`  4.5e-13   1.1e-7
``imse-rot`` :func:`sp.lpbwselect_imse_rot`  1.6e-12   1.2e-8
``ce-rot``   :func:`sp.lpbwselect_ce_rot`    4.2e-13   3.0e-9
===========  ==============================  ========  ==========

Stata's larger residual is its own: ``lpbwselect.ado`` integrates the
kernel moment constants numerically where these use closed forms. R is
therefore the tight pin and Stata the loose cross-check, not the reverse.

``ce-dpi`` is not ported; see :func:`sp.did_had`.

Tolerance
---------
1e-7 on all four reported quantities; observed worst case 9.2e-9. The
residual is float accumulation, not a convention difference: ``N`` agrees
exactly in every cell, which is the discrete check that both sides
selected the same observations.
"""

from __future__ import annotations

import json
import pathlib

import numpy as np
import pandas as pd
import pytest

import statspai as sp
from statspai.exceptions import MethodIncompatibility

_HERE = pathlib.Path(__file__).resolve().parents[1] / "stata_parity" / "option_parity"
_DATA = _HERE / "data_86_lprobust.csv"
_GOLDEN = _HERE / "results" / "86_lprobust_Stata.json"

ATOL = 1e-7


@pytest.fixture(scope="module")
def xy():
    d = pd.read_csv(_DATA)
    return d["d"].to_numpy(float), d["y"].to_numpy(float)


@pytest.fixture(scope="module")
def golden() -> dict:
    return {
        k: v
        for k, v in json.loads(_GOLDEN.read_text(encoding="utf-8")).items()
        if not k.startswith("_")
    }


@pytest.fixture(scope="module")
def bwgolden() -> dict:
    """Stata's bandwidth-SELECTION rows, keyed by bw_method() spelling."""
    return json.loads(_GOLDEN.read_text(encoding="utf-8"))["_bwselect"]


def _case_args(key: str):
    """Decode a fixture key into (kernel, h, b)."""
    if key.startswith("epa_h0.8_b"):
        return "epanechnikov", 0.8, float(key.rsplit("_b", 1)[1])
    kernel, hs = key.rsplit("_h", 1)
    h = float(hs)
    return kernel, h, h


class TestLprobustParity:
    def test_every_fixture_case_matches(self, xy, golden):
        x, y = xy
        worst = 0.0
        for key, want in golden.items():
            kernel, h, b = _case_args(key)
            got = sp.lprobust_at_point(x, y, 0.0, h=h, b=b, kernel=kernel)
            assert got.n_eff == want["N"], (
                f"{key}: effective N {got.n_eff} vs Stata {want['N']} — the "
                "two sides selected different observations"
            )
            for field in ("tau_us", "tau_bc", "se_us", "se_rb"):
                diff = abs(getattr(got, field) - want[field])
                worst = max(worst, diff)
                assert diff < ATOL, (
                    f"{key}.{field}: {getattr(got, field):.15f} vs Stata "
                    f"{want[field]:.15f} (diff {diff:.2e})"
                )
        assert worst < ATOL

    def test_fixture_covers_every_kernel_and_a_distinct_bias_bandwidth(self, golden):
        """Guard the fixture itself, not just the comparison."""
        kernels = {_case_args(k)[0] for k in golden}
        assert kernels == {"epanechnikov", "triangular", "uniform"}
        assert any(b != h for _, h, b in map(_case_args, golden)), (
            "at least one case must have b != h, or the union-window "
            "behaviour is never exercised"
        )

    def test_union_window_is_what_n_reports(self, xy, golden):
        """With b > h the fit spans the LARGER window.

        Reporting the h-window instead gives 241 where Stata gives 317 on
        this fixture. That is not cosmetic: those rows genuinely enter the
        bias-correction step, so a mismatch here means tau_bc is being
        computed on the wrong sample.
        """
        x, y = xy
        got = sp.lprobust_at_point(x, y, 0.0, h=0.8, b=1.2)
        assert got.n_eff == golden["epa_h0.8_b1.2"]["N"] == 317
        narrower = sp.lprobust_at_point(x, y, 0.0, h=0.8, b=0.8)
        assert narrower.n_eff == 241


class TestLprobustProperties:
    """Behaviour that parity alone does not pin."""

    def test_robust_se_exceeds_conventional(self, xy):
        """Bias correction costs variance; that is the whole trade."""
        x, y = xy
        got = sp.lprobust_at_point(x, y, 0.0, h=0.8)
        assert got.se_rb > got.se_us

    def test_bias_is_the_difference_of_the_two_fits(self, xy):
        x, y = xy
        got = sp.lprobust_at_point(x, y, 0.0, h=0.8)
        assert got.bias == pytest.approx(got.tau_us - got.tau_bc, abs=1e-15)

    def test_recovers_a_known_intercept(self):
        """Correctness beyond parity: both packages could be wrong together.

        A large, low-noise sample from a known function must return its
        value at the evaluation point.
        """
        rng = np.random.default_rng(11)
        x = np.abs(rng.gamma(1.4, 0.6, 8000))
        y = 2.5 + 1.3 * x - 0.4 * x**2 + rng.normal(0, 0.05, 8000)
        got = sp.lprobust_at_point(x, y, 0.0, h=0.5)
        assert got.tau_us == pytest.approx(2.5, abs=0.02)
        assert got.tau_bc == pytest.approx(2.5, abs=0.02)

    def test_default_bias_bandwidth_is_h(self, xy):
        x, y = xy
        assert sp.lprobust_at_point(x, y, 0.0, h=0.8).b == 0.8

    @pytest.mark.parametrize(
        "kernel,expected",
        [
            # Epanechnikov 0.75(1-u^2) and triangular (1-|u|) are ZERO at
            # |u| = 1, so the boundary point carries no weight and is not
            # in the window. Uniform is 0.5 there and keeps it. The window
            # is defined by w > 0 (as in lprobust), not by |u| <= 1, and
            # the two differ by exactly this point.
            #
            # Checked against Stata rather than inferred: on
            # x = 0, .25, .5, .5, 1, 1.25, ... with h = 1, lprobust
            # reports N = 4 / 4 / 5 for the three kernels.
            ("epanechnikov", 6),
            ("triangular", 6),
            ("uniform", 7),
        ],
    )
    def test_window_is_defined_by_positive_weight_not_by_distance(
        self, kernel, expected
    ):
        """A leaking boundary would silently widen the effective sample."""
        x = np.array([0.0, 0.2, 0.4, 0.5, 0.7, 0.9, 1.0, 1.5, 2.0, 2.5])
        y = np.arange(10.0)
        got = sp.lprobust_at_point(x, y, 0.0, h=1.0, kernel=kernel, n_neighbors=2)
        assert got.n_eff == expected

    def test_gaussian_kernel_has_no_compact_window(self):
        """Every observation carries weight, so n_eff is the whole sample."""
        x = np.array([0.0, 0.2, 0.4, 0.5, 0.7, 0.9, 1.0, 1.5, 2.0, 2.5])
        y = np.arange(10.0)
        got = sp.lprobust_at_point(x, y, 0.0, h=1.0, kernel="gaussian", n_neighbors=2)
        assert got.n_eff == len(x)


class TestLprobustValidation:
    def test_too_few_points_in_window_raises(self, xy):
        x, y = xy
        with pytest.raises(ValueError, match="fall inside the bandwidth"):
            sp.lprobust_at_point(x, y, 0.0, h=1e-6)

    @pytest.mark.parametrize("bad", [0.0, -1.0, np.nan, np.inf])
    def test_invalid_bandwidth_rejected(self, xy, bad):
        x, y = xy
        with pytest.raises(ValueError, match="positive finite bandwidth"):
            sp.lprobust_at_point(x, y, 0.0, h=bad)

    def test_unknown_kernel_rejected(self, xy):
        x, y = xy
        with pytest.raises(ValueError, match="kernel must be one of"):
            sp.lprobust_at_point(x, y, 0.0, h=0.8, kernel="biweight")

    def test_deriv_above_p_rejected(self, xy):
        x, y = xy
        with pytest.raises(ValueError, match="0 <= deriv <= p"):
            sp.lprobust_at_point(x, y, 0.0, h=0.8, p=1, deriv=2)

    def test_mismatched_lengths_rejected(self):
        with pytest.raises(ValueError, match="same length"):
            sp.lprobust_at_point(np.arange(10.0), np.arange(9.0), 0.0, h=1.0)

    def test_non_finite_rows_are_dropped_not_propagated(self, xy):
        x, y = xy
        xn, yn = x.copy(), y.copy()
        yn[0] = np.nan
        xn[1] = np.nan
        got = sp.lprobust_at_point(xn, yn, 0.0, h=0.8)
        assert np.isfinite(got.tau_us) and np.isfinite(got.se_rb)


class TestBandwidthSelection:
    """``mse-dpi`` direct-plug-in selection.

    Pinned against **R** ``nprobust::lpbwselect`` rather than Stata,
    because Stata's ``lprobust`` overrides the selector's ``b`` with
    ``h/rho`` (``rho`` defaults to 1) and so never reports the ``b`` the
    selector actually chose. R reports both, which is the stricter check
    — and R and Stata agree on ``h`` to 4e-9 anyway.

    The Stata implementation is a compiled Mata routine with no readable
    source; the R package implements the same algorithm in readable R,
    which is what this port was written from.
    """

    # nprobust::lpbwselect(y, x, eval=0, kernel="epa", bwselect="mse-dpi")
    R_H = 0.59287569069430
    R_B = 1.02131749854371

    def test_h_matches_r(self, xy):
        x, y = xy
        got = sp.lpbwselect_mse_dpi(x, y, 0.0)
        assert got["h"] == pytest.approx(self.R_H, abs=1e-10)

    def test_b_matches_r(self, xy):
        """The selector's own b, which Stata's rho=1 hides."""
        x, y = xy
        got = sp.lpbwselect_mse_dpi(x, y, 0.0)
        assert got["b"] == pytest.approx(self.R_B, abs=1e-10)

    def test_h_matches_stata_too(self, xy, bwgolden):
        x, y = xy
        got = sp.lpbwselect_mse_dpi(x, y, 0.0)
        assert got["h"] == pytest.approx(bwgolden["mse-dpi"]["h"], abs=1e-7)

    def test_b_exceeds_h_here(self, xy):
        """Pins that b and h are genuinely different objects.

        did_had uses h for BOTH, inheriting lprobust's rho=1. If a future
        change passed the selector's b as the bias bandwidth, every
        bias-correction window would silently widen.
        """
        x, y = xy
        got = sp.lpbwselect_mse_dpi(x, y, 0.0)
        assert got["b"] > got["h"]

    def test_selected_bandwidth_reproduces_the_default_fit(self, xy):
        """Selecting then fitting must equal fitting at the selected h."""
        x, y = xy
        bw = sp.lpbwselect_mse_dpi(x, y, 0.0)
        fit = sp.lprobust_at_point(x, y, 0.0, h=bw["h"], b=bw["h"])
        assert np.isfinite(fit.tau_us) and fit.se_rb > 0

    def test_even_case_is_rejected_not_approximated(self, xy):
        """(p - deriv) even needs an optimization step that is not ported."""
        x, y = xy
        with pytest.raises(MethodIncompatibility, match="odd"):
            sp.lpbwselect_mse_dpi(x, y, 0.0, p=2, deriv=0)

    def test_too_few_observations_for_bwcheck_raises(self):
        rng = np.random.default_rng(3)
        x = np.abs(rng.gamma(1.4, 0.6, 10))
        with pytest.raises(ValueError, match="bwcheck"):
            sp.lpbwselect_mse_dpi(x, rng.normal(size=10), 0.0)

    @pytest.mark.parametrize("kernel", ["epanechnikov", "triangular", "uniform"])
    def test_every_kernel_selects_a_usable_bandwidth(self, xy, kernel):
        x, y = xy
        got = sp.lpbwselect_mse_dpi(x, y, 0.0, kernel=kernel)
        assert got["h"] > 0 and np.isfinite(got["h"])


class TestRuleOfThumbSelection:
    """``mse-rot``, the cheap selector.

    Both Stata commands report ``h`` here and both agree with R, so this
    pins against all three. Stata's residual (5.1e-8, against 4.3e-12 for
    R) is its own: ``lpbwselect.ado`` integrates the kernel moment
    constants numerically where this port evaluates them in closed form.
    """

    # nprobust::lpbwselect(y, x, eval=0, kernel="epa", bwselect="mse-rot")
    R_H = 0.82250763869293

    def test_h_matches_r(self, xy):
        x, y = xy
        got = sp.lpbwselect_mse_rot(x, y, 0.0)
        assert got["h"] == pytest.approx(self.R_H, abs=1e-10)

    def test_h_matches_stata_too(self, xy, bwgolden):
        x, y = xy
        got = sp.lpbwselect_mse_rot(x, y, 0.0)
        assert got["h"] == pytest.approx(bwgolden["mse-rot"]["h"], abs=1e-7)

    def test_no_b_is_reported(self, xy):
        """R's rot 'b' (3.93756301237494) is deliberately not ported.

        R obtains it by re-entering the selector at p = q = deriv + 1,
        which lands on the even (p - deriv) branch this port rejects.
        Neither consumer needs it — Stata's lprobust and did_had both run
        rho = 1, so their bias bandwidth is h. This pins that the key is
        ABSENT rather than silently wrong: a future change that starts
        returning some other b must come here and justify it.
        """
        x, y = xy
        assert "b" not in sp.lpbwselect_mse_rot(x, y, 0.0)

    def test_the_b_branch_is_what_is_unported(self, xy):
        """The exact call R makes for b is the one that raises."""
        x, y = xy
        with pytest.raises(MethodIncompatibility, match="odd"):
            sp.lpbwselect_mse_rot(x, y, 0.0, p=2, deriv=2)

    def test_stata_reports_b_equal_to_h(self, bwgolden):
        """Pins the rho=1 convention the port relies on.

        If a future Stata release started reporting the selector's own b
        here, did_had's 'h for both' would stop matching, and this says
        so directly instead of surfacing as a drifted estimate.
        """
        for sel in ("mse-dpi", "mse-rot"):
            assert bwgolden[sel]["b"] == bwgolden[sel]["h"]

    def test_rot_is_wider_than_dpi_here(self, xy):
        """The two selectors are distinct, not aliases.

        A refactor that quietly routed 'mse-rot' to the dpi selector
        would still pass every smoke test; this is what catches it.
        """
        x, y = xy
        assert (
            sp.lpbwselect_mse_rot(x, y, 0.0)["h"]
            > sp.lpbwselect_mse_dpi(x, y, 0.0)["h"]
        )

    def test_selected_bandwidth_reproduces_the_stata_fit(self, xy, bwgolden):
        """End-to-end: select, then fit at rho=1, against Stata's own row.

        The two halves are pinned separately above; this is the check
        that composing them lands where Stata lands.
        """
        x, y = xy
        want = bwgolden["mse-rot"]
        bw = sp.lpbwselect_mse_rot(x, y, 0.0)
        fit = sp.lprobust_at_point(x, y, 0.0, h=bw["h"], b=bw["h"])
        assert fit.n_eff == want["N"] == 243
        assert fit.tau_us == pytest.approx(want["tau_us"], abs=1e-7)
        assert fit.se_us == pytest.approx(want["se_us"], abs=1e-7)

    def test_even_case_is_rejected_not_approximated(self, xy):
        x, y = xy
        with pytest.raises(MethodIncompatibility, match="odd"):
            sp.lpbwselect_mse_rot(x, y, 0.0, p=2, deriv=0)

    def test_mismatched_lengths_rejected(self):
        with pytest.raises(ValueError, match="same length"):
            sp.lpbwselect_mse_rot(np.arange(10.0), np.arange(9.0), 0.0)

    def test_too_few_observations_rejected(self):
        with pytest.raises(ValueError, match="global polynomial"):
            sp.lpbwselect_mse_rot(np.arange(4.0), np.arange(4.0), 0.0)

    def test_gaussian_kernel_rejected(self, xy):
        """Closed-form moments cover the compact kernels only."""
        x, y = xy
        with pytest.raises(ValueError):
            sp.lpbwselect_mse_rot(x, y, 0.0, kernel="gaussian")

    @pytest.mark.parametrize("kernel", ["epanechnikov", "triangular", "uniform"])
    def test_every_kernel_selects_a_usable_bandwidth(self, xy, kernel):
        x, y = xy
        got = sp.lpbwselect_mse_rot(x, y, 0.0, kernel=kernel)
        assert got["h"] > 0 and np.isfinite(got["h"])


class TestIntegratedAndCoverageSelectors:
    """``imse-dpi``, ``imse-rot`` and ``ce-rot``.

    R values from ``nprobust::lpbwselect(y, x, eval=0, kernel="epa",
    bwselect=<s>, p=1, deriv=0)``. Stata agrees with R on all of these
    (worst 1.1e-7), so both are pinned; the ports sit within 1.6e-12 of R.
    """

    R = {
        "imse-dpi": {"h": 2.46327467697411, "b": 3.19519419568710},
        "imse-rot": {"h": 1.08307730989932},
        "ce-rot": {"h": 0.43940059841162, "b": 0.59960680273881},
    }

    def _call(self, name, x, y):
        if name == "imse-dpi":
            return sp.lpbwselect_imse_dpi(x, y)
        if name == "imse-rot":
            return sp.lpbwselect_imse_rot(x, y)
        return sp.lpbwselect_ce_rot(x, y, 0.0)

    @pytest.mark.parametrize("name", ["imse-dpi", "imse-rot", "ce-rot"])
    def test_h_matches_r(self, xy, name):
        x, y = xy
        assert self._call(name, x, y)["h"] == pytest.approx(
            self.R[name]["h"], abs=1e-10
        )

    @pytest.mark.parametrize("name", ["imse-dpi", "ce-rot"])
    def test_b_matches_r(self, xy, name):
        x, y = xy
        assert self._call(name, x, y)["b"] == pytest.approx(self.R[name]["b"], abs=1e-9)

    def test_imse_rot_reports_no_b(self, xy):
        """Same unported even-branch reason as mse-rot."""
        x, y = xy
        assert "b" not in sp.lpbwselect_imse_rot(x, y)

    def test_ce_rot_undersmooths_mse_dpi(self, xy):
        """The whole point of a coverage-error bandwidth.

        ce-rot is mse-dpi scaled by N^(-p/((2p+3)(p+3))) < 1, so h must
        come in strictly below. If a refactor dropped the exponent the
        two would coincide and every interval would silently widen.
        """
        x, y = xy
        assert sp.lpbwselect_ce_rot(x, y, 0.0)["h"] < (
            sp.lpbwselect_mse_dpi(x, y, 0.0)["h"]
        )

    def test_ce_rot_is_exactly_the_documented_rescaling(self, xy):
        """Pin the closed form, not just its direction."""
        x, y = xy
        p, q, n = 1, 2, len(x)
        mse = sp.lpbwselect_mse_dpi(x, y, 0.0)
        ce = sp.lpbwselect_ce_rot(x, y, 0.0)
        assert ce["h"] == pytest.approx(
            mse["h"] * n ** (-(p / ((2 * p + 3) * (p + 3)))), abs=1e-14
        )
        assert ce["b"] == pytest.approx(
            mse["b"] * n ** (-((q + 2) / ((2 * q + 5) * (q + 3)))), abs=1e-14
        )

    def test_ce_rot_rescales_by_the_sample_actually_used(self, xy):
        """N must count rows mse-dpi kept, not rows with finite x.

        A missing y drops the row inside mse-dpi, so counting finite x
        alone would rescale by too large an N. Dropping the row by hand
        must give exactly the same answer as leaving it in as NaN.
        """
        x, y = xy
        y_holed = y.copy()
        y_holed[:5] = np.nan
        with_nan = sp.lpbwselect_ce_rot(x, y_holed, 0.0)
        dropped = sp.lpbwselect_ce_rot(x[5:], y[5:], 0.0)
        assert with_nan["h"] == pytest.approx(dropped["h"], abs=1e-14)
        assert with_nan["b"] == pytest.approx(dropped["b"], abs=1e-14)

    def test_the_two_imse_grids_are_not_interchangeable(self, xy):
        """imse-rot uses x-quantiles; imse-dpi uses equal spacing.

        The reference is inconsistent here and this port follows it. A
        well-meaning harmonization would move one of the two numbers off
        R, so pin that they genuinely differ on this fixture.
        """
        x, y = xy
        assert sp.lpbwselect_imse_rot(x, y)["h"] != pytest.approx(
            sp.lpbwselect_imse_dpi(x, y)["h"], abs=1e-6
        )

    def test_imse_is_global_not_pointwise(self, xy):
        """No eval_point argument at all — that is the definition."""
        import inspect

        for fn in (sp.lpbwselect_imse_dpi, sp.lpbwselect_imse_rot):
            assert "eval_point" not in inspect.signature(fn).parameters

    def test_imse_dpi_grid_size_changes_the_answer(self, xy):
        """imsegrid is a real knob, not decoration."""
        x, y = xy
        assert sp.lpbwselect_imse_dpi(x, y, imsegrid=30)["h"] != pytest.approx(
            sp.lpbwselect_imse_dpi(x, y, imsegrid=12)["h"], abs=1e-9
        )

    @pytest.mark.parametrize("bad", [0, 1, -5])
    def test_imse_dpi_rejects_a_degenerate_grid(self, xy, bad):
        x, y = xy
        with pytest.raises(ValueError, match="imsegrid"):
            sp.lpbwselect_imse_dpi(x, y, imsegrid=bad)

    @pytest.mark.parametrize("name", ["imse-dpi", "imse-rot", "ce-rot"])
    def test_even_case_is_rejected_not_approximated(self, xy, name):
        x, y = xy
        with pytest.raises(MethodIncompatibility, match="odd"):
            if name == "imse-dpi":
                sp.lpbwselect_imse_dpi(x, y, p=2, deriv=0)
            elif name == "imse-rot":
                sp.lpbwselect_imse_rot(x, y, p=2, deriv=0)
            else:
                sp.lpbwselect_ce_rot(x, y, 0.0, p=2, deriv=0)

    @pytest.mark.parametrize("name", ["imse-dpi", "imse-rot"])
    def test_mismatched_lengths_rejected(self, name):
        fn = sp.lpbwselect_imse_dpi if name == "imse-dpi" else sp.lpbwselect_imse_rot
        with pytest.raises(ValueError, match="same length"):
            fn(np.arange(10.0), np.arange(9.0))
