"""``sp.event_study_vcov`` on ``sp.did_imputation`` against Stata.

The reference is Stata 18 ``did_imputation`` (Borusyak, SSC) on Track A
module 05's CSV bytes, generated by
``_fixtures/_generate_did_imputation_vcov_Stata.do``. ``did_imputation``
iterates twice, and the two iterations explain everything below:

* Its imputation weights run to ``tol(1e-6)`` / ``maxit(100)`` by default.
  They drive ``e(V)``. The generator tightens them to ``tol(1e-12)`` /
  ``maxit(100000)``, and the covariance then matches to 1.2e-9. (The older
  fixture in ``tests/fixtures/es_inference/``, at the defaults, was held
  to 2e-5.)
* ``reghdfe`` solves the fixed effects to its own tolerance, 1e-8, which
  ``did_imputation`` does not expose. That leaves ``e(b)`` 3.6e-7 relative
  from the exact least-squares imputation. The generator therefore also
  computes the exact imputation in Stata (dense ``regress`` on unit and year
  dummies over untreated rows, ``b_exact``); StatsPAI matches that to
  1.0e-11, which locates the whole ``e(b)`` gap in the reghdfe solver.
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import statspai as sp

_ROOT = Path(__file__).resolve().parents[2]
_FIXTURE = (
    Path(__file__).resolve().parent / "_fixtures" / "did_imputation_vcov_Stata.json"
)
_MPDTA = _ROOT / "tests" / "r_parity" / "data" / "05_sunab.csv"


@pytest.fixture(scope="module")
def ref():
    return json.loads(_FIXTURE.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def es():
    mp = pd.read_csv(_MPDTA)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        fit = sp.did_imputation(
            mp,
            y="lemp",
            group="countyreal",
            time="year",
            first_treat="first_treat",
            horizon=[0, 1, 2, 3],
        )
    return sp.event_study_vcov(fit)


def test_joint_covariance_matches_stata_did_imputation(es, ref):
    """Every entry of e(V); observed 1.2e-9, budget 1e-8."""
    assert es.times.tolist() == ref["horizons"]
    assert es.joint
    np.testing.assert_allclose(es.vcov, np.asarray(ref["V"]), rtol=1e-8, atol=0)


def test_horizon_effects_match_the_exact_imputation_in_stata(es, ref):
    """Stata's dense least-squares imputation; observed 1.0e-11."""
    np.testing.assert_allclose(es.beta, ref["b_exact"], rtol=1e-9, atol=0)


def test_horizon_effects_match_did_imputation_within_its_solver_tolerance(es, ref):
    """did_imputation's own e(b); observed 3.6e-7, the reghdfe solver.

    Budget is the Track A default of 1e-6. The gap is not StatsPAI's: the
    same Stata session's exact imputation (previous test) sits 1e-11 away.
    """
    np.testing.assert_allclose(es.beta, ref["b"], rtol=1e-6, atol=0)
    b, exact = np.asarray(ref["b"]), np.asarray(ref["b_exact"])
    assert np.max(np.abs(b - exact) / np.abs(exact)) > 1e-8
