"""``sp.honest_did(l_vec=, window=)`` against Stata ``honestdid``.

Reference: Stata 18 ``honestdid`` 1.3.0 (Caceres Bravo's port of Rambachan
& Roth's HonestDiD) on the ``jwdid ..., never`` event study of
``_fixtures/etwfe_poisson_jwdid_hettype.csv`` restricted to event times
-4..3 (``estat event, window(-4 3)``), generated by
``_fixtures/_generate_honest_did_lvec_window_Stata.do``.  Targets: the
average of the four horizons and the single horizon ``e = 1``.

StatsPAI's side is ``sp.etwfe(family='poisson', fe='unit',
cgroup='nevertreated', separated='drop')`` -- ppmlhdfe flags this panel's
all-zero units, see ``test_etwfe_poisson_jwdid_parity.py`` -- whose
event-time coefficients equal Stata's ``r(b)`` to 1e-14, so both sides
start from the same inputs.

Tolerances: the FLCI is the same convex program on both sides; Stata's
folded-normal quantile is simulated, which leaves ~3e-6, held to 1e-5.
The Conditional relative-magnitudes set is deterministic, but its bounds
are grid points and the two implementations lay the grid differently
(StatsPAI follows R HonestDiD's 1,000 points over +/-20 SD of the target;
the Stata port picks its range from the estimates), so each bound is held
to one of StatsPAI's grid steps.
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import statspai as sp
from statspai.exceptions import MethodIncompatibility

_FIX = Path(__file__).resolve().parent / "_fixtures"
WINDOW = (-4, 3)


@pytest.fixture(scope="module")
def ref():
    return json.loads(
        (_FIX / "honest_did_lvec_window_Stata.json").read_text(encoding="utf-8")
    )


@pytest.fixture(scope="module")
def fit():
    df = pd.read_csv(_FIX / "etwfe_poisson_jwdid_hettype.csv")
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return sp.etwfe(
            df,
            y="y",
            group="id",
            time="year",
            first_treat="g",
            family="poisson",
            fe="unit",
            scale="link",
            cgroup="nevertreated",
            separated="drop",
        )


def _moments(fit):
    evc = sp.event_study_vcov(fit, allow_diagonal=False)
    w = (evc.times >= WINDOW[0]) & (evc.times <= WINDOW[1])
    return evc.beta[w], evc.vcov[np.ix_(w, w)], evc.times[w]


def test_inputs_equal_stata(ref, fit):
    b, _, t = _moments(fit)
    assert list(t) == [-4, -3, -2, 0, 1, 2, 3]
    np.testing.assert_allclose(b, ref["b"], rtol=0, atol=1e-12)


@pytest.mark.parametrize(
    "name, kw",
    [
        ("sd_avg", {"l_vec": "average"}),
        ("sd_e1", {"e": 1}),
    ],
)
def test_flci_matches_stata(ref, fit, name, kw):
    R = ref[name]
    out = sp.honest_did(fit, method="smoothness", window=WINDOW, m_grid=R["M"], **kw)
    assert out.attrs["interval"] == "flci"
    np.testing.assert_allclose(out["ci_lower"], R["lb"], rtol=0, atol=1e-5)
    np.testing.assert_allclose(out["ci_upper"], R["ub"], rtol=0, atol=1e-5)


@pytest.mark.parametrize(
    "name, kw, lvec",
    [
        ("rm_avg", {"l_vec": "average"}, np.full(4, 0.25)),
        ("rm_e1", {"e": 1}, np.array([0.0, 1.0, 0.0, 0.0])),
    ],
)
def test_conditional_rm_matches_stata(ref, fit, name, kw, lvec):
    R = ref[name]
    out = sp.honest_did(
        fit,
        method="relative_magnitude",
        honestdid_method="Conditional",
        window=WINDOW,
        m_grid=R["M"],
        **kw,
    )
    _, S, t = _moments(fit)
    post = S[np.ix_(t >= 0, t >= 0)]
    step = 40.0 * float(np.sqrt(lvec @ post @ lvec)) / 999.0
    np.testing.assert_allclose(out["ci_lower"], R["lb"], rtol=0, atol=step)
    np.testing.assert_allclose(out["ci_upper"], R["ub"], rtol=0, atol=step)


def test_l_vec_forms_agree(fit):
    avg = sp.honest_did(fit, l_vec="average", window=WINDOW, m_grid=[0.0, 0.02])
    explicit = sp.honest_did(fit, l_vec=[0.25] * 4, window=WINDOW, m_grid=[0.0, 0.02])
    pd.testing.assert_frame_equal(avg, explicit)
    one = sp.honest_did(fit, l_vec=[0, 1, 0, 0], window=WINDOW, m_grid=[0.0, 0.02])
    e1 = sp.honest_did(fit, e=1, window=WINDOW, m_grid=[0.0, 0.02])
    pd.testing.assert_frame_equal(one, e1)


def test_window_is_the_windowed_event_study(fit):
    """``window`` equals running the solvers on the windowed moments, and
    it matters: ``'average'`` then spans horizons 0..3, not 0..4."""
    from statspai.did._flci import flci_delta_sd

    b, S, t = _moments(fit)
    pm = t >= 0
    order = np.r_[np.flatnonzero(~pm), np.flatnonzero(pm)]
    direct = flci_delta_sd(
        b[order],
        S[np.ix_(order, order)],
        n_pre=int((~pm).sum()),
        n_post=int(pm.sum()),
        m_bar=0.02,
        l_post=np.full(int(pm.sum()), 0.25),
    )
    win = sp.honest_did(fit, l_vec="average", window=WINDOW, m_grid=[0.02])
    assert win["ci_lower"].iloc[0] == pytest.approx(direct.ci_lower, abs=1e-12)
    assert win["ci_upper"].iloc[0] == pytest.approx(direct.ci_upper, abs=1e-12)
    full = sp.honest_did(fit, l_vec="average", m_grid=[0.02])
    assert abs(full["ci_upper"].iloc[0] - win["ci_upper"].iloc[0]) > 1e-3


def test_invalid_l_vec_and_window(fit):
    with pytest.raises(MethodIncompatibility, match="weights"):
        sp.honest_did(fit, l_vec=[1, 0], window=WINDOW)
    with pytest.raises(MethodIncompatibility, match="'average'"):
        sp.honest_did(fit, l_vec="median")
    with pytest.raises(MethodIncompatibility, match="leads and horizons"):
        sp.honest_did(fit, window=(0, 3))
    with pytest.raises(MethodIncompatibility, match="native"):
        sp.honest_did(fit, backend="r", l_vec="average")
