"""Linear ``sp.etwfe(hettype= | fe='unit')`` against Stata ``jwdid``.

Reference: Stata 18, ``jwdid`` v2.201 / ``jwdid_estat`` v2.2 without
``method()`` -- ``reghdfe`` 6.12.3 absorbing ``ivar`` and ``tvar``,
clustered on ``ivar`` -- on ``_fixtures/etwfe_linear_jwdid_hettype.csv``
(360 units x 8 years, cohorts 2004 / 2006 / never, 80 missing outcomes so
the panel is unbalanced, a categorical ``xcat`` and a time-varying ``xc``),
generated by ``_fixtures/_generate_etwfe_linear_jwdid_Stata.do``.  The same
thirteen specifications as the Poisson fixture: every ``hettype()``,
``never``, covariates and their combinations; ``estat simple``,
``estat event`` and ``estat simple, over(xcat)``.

The linear model is OLS, closed form on both sides: estimates are held to
1e-10 and SEs to 1e-9 relative (reghdfe's small-sample factor
``(N-1)/(N-K) * G/(G-1)`` with ``K`` the regressors plus the constant; the
unit effects are nested in the cluster and not counted).
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import pytest

import statspai as sp
from statspai.exceptions import MethodIncompatibility

_FIX = Path(__file__).resolve().parent / "_fixtures"

SPECS = {
    "default": {"fe": "unit"},
    "event": {"hettype": "event"},
    "cohort": {"hettype": "cohort"},
    "time": {"hettype": "time"},
    "twfe": {"hettype": "twfe"},
    "never": {"fe": "unit", "cgroup": "nevertreated"},
    "never_cohort": {"cgroup": "nevertreated", "hettype": "cohort"},
    "never_event": {"cgroup": "nevertreated", "hettype": "event"},
    "xcat": {"fe": "unit", "xvar": "xcat"},
    "xc": {"fe": "unit", "xvar": "xc"},
    "xcat_event": {"xvar": "xcat", "hettype": "event"},
    "xcat_never": {"fe": "unit", "xvar": "xcat", "cgroup": "nevertreated"},
    "xcat_xc": {"fe": "unit", "xvar": ["xcat", "xc"]},
}


@pytest.fixture(scope="module")
def ref():
    return json.loads(
        (_FIX / "etwfe_linear_jwdid_Stata.json").read_text(encoding="utf-8")
    )


@pytest.fixture(scope="module")
def panel():
    df = pd.read_csv(_FIX / "etwfe_linear_jwdid_hettype.csv")
    df["xcat"] = df["xcat"].astype("category")
    return df


def _fit(df, **kw):
    return sp.etwfe(df, y="y", group="id", time="year", first_treat="g", **kw)


@pytest.mark.parametrize("name", list(SPECS))
def test_matches_jwdid_reghdfe(ref, panel, name):
    r = _fit(panel, **SPECS[name])
    R = ref[name]
    assert r.n_obs == R["N"]
    assert r.model_info["n_clusters"] == R["N_clust"]
    assert r.estimate == pytest.approx(R["simple"]["b"][0], rel=1e-10, abs=1e-12)
    assert r.se == pytest.approx(R["simple"]["se"][0], rel=1e-9)
    ev = r.model_info["aggregations"]["link"]["event"].set_index("relative_time")
    first = int(ev.index.min())
    for k, (b, se) in enumerate(zip(R["event"]["b"], R["event"]["se"])):
        if se == 0:
            continue  # the omitted reference period under never
        assert ev.loc[first + k, "att"] == pytest.approx(b, rel=1e-10, abs=1e-12)
        assert ev.loc[first + k, "se"] == pytest.approx(se, rel=1e-9)
    if "over" in R:
        by = sp.etwfe_emfx(r, type="simple", by_xvar=True).detail.set_index("level")
        for lev, b, se in zip(sorted(by.index), R["over"]["b"], R["over"]["se"]):
            assert by.loc[lev, "att"] == pytest.approx(b, rel=1e-10, abs=1e-12)
            assert by.loc[lev, "se"] == pytest.approx(se, rel=1e-9)


def test_default_linear_design_is_unchanged(panel):
    """Without hettype= / fe= the linear sp.etwfe stays R etwfe's cohort
    design (the historical path)."""
    r = _fit(panel.dropna(subset=["y"]))
    assert r.model_info.get("estimator") != "etwfe_glm"


def test_linear_hettype_rejects_unsupported_options(panel):
    with pytest.raises(MethodIncompatibility, match="weights"):
        _fit(panel.assign(w=1.0), hettype="event", weights="w")
    with pytest.raises(MethodIncompatibility, match="separated"):
        _fit(panel, hettype="event", separated="drop")
