"""Reference parity: ``sp`` Kaplan-Meier / log-rank vs R ``survival``.

These two non-parametric survival routines are pinned to *exact* R numbers
on a shared fixed design (``survival_km_data.csv``, tie-free):

  * ``sp.kaplan_meier`` -> ``survival::survfit`` — the product-limit survival
    estimate evaluated at fixed query times, per group, plus the median
    survival time.
  * ``sp.logrank_test`` -> ``survival::survdiff`` — the Mantel-Haenszel
    log-rank chi-square, its df, and the p-value.

Tolerances / conventions
------------------------
  * KM survival at the query times: 1e-9 relative. The product-limit
    estimator is a deterministic step function; on a tie-free sample sp and
    survfit must agree to numerical precision. The step value at a query time
    ``q`` is the survival at the largest event time ``<= q`` (R's
    ``summary(fit, times = q, extend = TRUE)``).
  * Log-rank chi-square / p-value: 1e-6 relative. The Mantel-Haenszel
    statistic and its variance are unambiguous without ties.
  * Median survival: 1e-6 relative (smallest time with survival <= 0.5;
    identical convention in both implementations on this design).

The fixture is regenerated by
``_generate_survival_km_data.py`` (data) and ``_generate_survival_km.R``
(R reference). The committed ``survival_km_R.json`` is what this test reads;
R is not required to run the test.

References
----------
- Therneau, T. M. & Grambsch, P. M. (2000). *Modeling Survival Data:
  Extending the Cox Model*. Springer (the R ``survival`` package).
  doi:10.1007/978-1-4757-3294-8
"""

from __future__ import annotations

import json
import pathlib

import numpy as np
import pandas as pd
import pytest

import statspai as sp

_FIXTURE_DIR = pathlib.Path(__file__).parent / "_fixtures"


@pytest.fixture(scope="module")
def km_data():
    return pd.read_csv(_FIXTURE_DIR / "survival_km_data.csv")


@pytest.fixture(scope="module")
def r_reference():
    with open(_FIXTURE_DIR / "survival_km_R.json", encoding="utf-8") as f:
        return json.load(f)


def _km_step(table: pd.DataFrame, q: float) -> float:
    """Survival at the largest event time <= q (right-continuous step)."""
    sub = table[table["time"] <= q]
    return float(sub.iloc[-1]["survival"])


# --------------------------------------------------------------------------
# Kaplan-Meier survival curve (sp.kaplan_meier == survival::survfit)
# --------------------------------------------------------------------------
def test_km_survival_matches_survfit(km_data, r_reference):
    km = sp.kaplan_meier(km_data, duration="time", event="status", group="group")
    tab = km.survival_table
    for gv in ("0", "1"):
        gtab = tab[tab["group"].astype(str) == gv].sort_values("time")
        ref = r_reference["km"][gv]
        for q, s_r in zip(ref["times"], ref["surv"]):
            s_sp = _km_step(gtab, float(q))
            assert s_sp == pytest.approx(s_r, rel=1e-9, abs=1e-12), (gv, q)


def test_km_median_matches_survfit(km_data, r_reference):
    km = sp.kaplan_meier(km_data, duration="time", event="status", group="group")
    for gv in ("0", "1"):
        med_sp = float(km.median_survival[gv])
        med_r = float(r_reference["km"][gv]["median"])
        assert med_sp == pytest.approx(med_r, rel=1e-6), gv


# --------------------------------------------------------------------------
# Log-rank test (sp.logrank_test == survival::survdiff)
# --------------------------------------------------------------------------
def test_logrank_chisq_matches_survdiff(km_data, r_reference):
    lr = sp.logrank_test(km_data, duration="time", event="status", group="group")
    ref = r_reference["logrank"]
    assert lr["df"] == ref["df"]
    assert float(lr["test_statistic"]) == pytest.approx(ref["chisq"], rel=1e-6)
    assert float(lr["p_value"]) == pytest.approx(ref["p_value"], rel=1e-6)


def test_logrank_observed_events_match(km_data, r_reference):
    lr = sp.logrank_test(km_data, duration="time", event="status", group="group")
    obs = lr["observed_events"]
    obs_vals = list(obs.values()) if isinstance(obs, dict) else list(np.ravel(obs))
    assert sum(float(v) for v in obs_vals) == pytest.approx(
        sum(r_reference["logrank"]["observed"]), rel=1e-9
    )
