"""Reference parity: dynamic-panel GMM against Stata 18 on ``abdata``.

Dataset
-------
``_fixtures/dynpanel_abdata.csv`` is Stata's ``webuse abdata`` — the
Arellano & Bond (1991) panel of 140 UK firms, 1976-1984, unbalanced and
ragged (7-9 observations per firm).  It is exported in ``%21.16e`` so
Python estimates on *the same bytes* Stata did; nothing is re-simulated,
so a mismatch is a genuine numerical disagreement and not a DGP artefact.

Reference
---------
``_fixtures/dynpanel_stata.json``, generated by
``_fixtures/_generate_dynpanel_stata.do`` (Stata 18 MP, plus ``xtabond2``
from SSC) and folded by ``_fixtures/_fold_dynpanel_stata.py``.  Each spec
carries the full coefficient vector, its standard errors, and the
``e()`` scalars (``N``, ``zrank``/``j``, ``arm1``, ``arm2``, ``sargan``).

Why this file exists
--------------------
``sp.xtabond``'s only prior numeric guarantee was a self-consistency check
against ``sp.gmm`` plus a Monte-Carlo recovery band.  Neither would have
caught the defect this suite was written to lock out: because the
estimator applied a listwise ``dropna`` across ``[id, time, y] + x``
*before* building anything, a lagged covariate's leading ``NaN``s deleted
the corresponding ``y`` levels from the **instrument** pool.  Reproducing
the Arellano-Bond (1991) Table 4 specification therefore used 19 of 32
instruments and 331 of 611 observations, and returned rho = 0.660 where
Stata returns 0.849 — a 22% error that no recovery band would flag.

Tolerance
---------
``rtol = 1e-9``.  These are the same closed-form linear-algebra
operations on the same doubles, so agreement is limited only by BLAS
reassociation; probed worst case across all specs below is ~1e-10 on a
coefficient whose value is 5e-4 (the ``yr1984`` dummy), and ~3e-12
elsewhere.  Anything looser would let a real convention change hide.

References
----------
Arellano, M. and Bond, S. (1991). *Review of Economic Studies* 58(2),
277-297. [@arellano1991some]
Roodman, D. (2009). How to do xtabond2. *Stata Journal* 9(1), 86-136.
[@roodman2009xtabond]
Windmeijer, F. (2005). *Journal of Econometrics* 126(1), 25-51.
[@windmeijer2005finite]
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import statspai as sp

FIXTURES = Path(__file__).parent / "_fixtures"
DATA_CSV = FIXTURES / "dynpanel_abdata.csv"
STATA_JSON = FIXTURES / "dynpanel_stata.json"
R_JSON = FIXTURES / "dynpanel_R.json"

RTOL = 1e-9

# StatsPAI labels lagged terms "L1.x"; Stata prints the first lag as "L.x".
_NAME_MAP = {"L1.n": "L.n", "L1.w": "L.w", "L1.k": "L.k"}

pytestmark = pytest.mark.skipif(
    not (DATA_CSV.exists() and STATA_JSON.exists()),
    reason="dynamic-panel Stata fixture not generated",
)


@pytest.fixture(scope="module")
def abdata() -> pd.DataFrame:
    return pd.read_csv(DATA_CSV)


@pytest.fixture(scope="module")
def stata() -> dict:
    return json.loads(STATA_JSON.read_text(encoding="utf-8"))


def _fit(abdata, **kwargs):
    with warnings.catch_warnings():
        # Instrument-count and gap advisories are diagnostics, not the
        # subject of these tests.
        warnings.simplefilter("ignore")
        return sp.xtabond(abdata, y="n", id="id", time="year", **kwargs)


def _assert_matches(result, ref: dict, spec: str) -> None:
    """Every coefficient and SE StatsPAI reports must match Stata's."""
    got_names = list(result.detail["variable"])
    matched = 0
    for i, name in enumerate(got_names):
        key = _NAME_MAP.get(name, name)
        assert key in ref["coef"], (
            f"[{spec}] StatsPAI reports a term {name!r} that Stata does not "
            f"({sorted(ref['coef'])}); the two designs differ."
        )
        np.testing.assert_allclose(
            float(result.detail["coefficient"].iloc[i]),
            ref["coef"][key],
            rtol=RTOL,
            atol=1e-12,
            err_msg=f"[{spec}] coefficient on {name} differs from Stata.",
        )
        np.testing.assert_allclose(
            float(result.detail["se"].iloc[i]),
            ref["se"][key],
            rtol=RTOL,
            atol=1e-12,
            err_msg=f"[{spec}] standard error on {name} differs from Stata.",
        )
        matched += 1
    assert matched == len(ref["coef"]), (
        f"[{spec}] Stata reports {len(ref['coef'])} terms but StatsPAI "
        f"reports {matched}: {got_names}."
    )


def _assert_sample(result, ref: dict, spec: str, instrument_key: str = "zrank") -> None:
    e = ref["e"]
    assert result.model_info["n_obs"] == int(e["N"]), (
        f"[{spec}] differenced sample size {result.model_info['n_obs']} != "
        f"Stata's e(N) {int(e['N'])} — the row-inclusion rule differs."
    )
    if instrument_key in e:
        assert result.model_info["n_instruments"] == int(e[instrument_key]), (
            f"[{spec}] instrument count {result.model_info['n_instruments']} "
            f"!= Stata's e({instrument_key}) {int(e[instrument_key])}."
        )


# ---------------------------------------------------------------------------
# A. Difference GMM baselines (pure AR(p), no covariates).
# ---------------------------------------------------------------------------


class TestDifferenceGMMBaseline:
    def test_ar1_onestep_robust(self, abdata, stata):
        spec = "A1_ar1_1step_robust"
        r = _fit(abdata, lags=1, twostep=False, robust=True)
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec)

    def test_ar1_onestep_classical(self, abdata, stata):
        spec = "A2_ar1_1step_classic"
        r = _fit(abdata, lags=1, twostep=False, robust=False)
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec)

    def test_ar2_onestep_robust(self, abdata, stata):
        spec = "A3_ar2_1step_robust"
        r = _fit(abdata, lags=2, twostep=False, robust=True)
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec)

    def test_ar1_twostep_windmeijer(self, abdata, stata):
        """The Windmeijer (2005) correction, not just the point estimate."""
        spec = "A4_ar1_2step_wc"
        r = _fit(abdata, lags=1, twostep=True, robust=True)
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec)

    def test_ar1_twostep_conventional(self, abdata, stata):
        spec = "A5_ar1_2step_conv"
        r = _fit(abdata, lags=1, twostep=True, robust=False)
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec)


# ---------------------------------------------------------------------------
# B. Serial-correlation and over-identification diagnostics.
# ---------------------------------------------------------------------------


class TestDiagnostics:
    def test_ar_tests_onestep_robust(self, abdata, stata):
        """e(arm1)/e(arm2) — the tests that decide whether the design holds."""
        spec = "A1_ar1_1step_robust"
        r = _fit(abdata, lags=1, twostep=False, robust=True)
        e = stata[spec]["e"]
        np.testing.assert_allclose(
            [r.model_info["ar1_z"], r.model_info["ar2_z"]],
            [e["arm1"], e["arm2"]],
            rtol=1e-7,
            err_msg=f"[{spec}] Arellano-Bond AR z statistics differ from Stata.",
        )

    def test_ar_tests_onestep_classical(self, abdata, stata):
        spec = "A2_ar1_1step_classic"
        r = _fit(abdata, lags=1, twostep=False, robust=False)
        e = stata[spec]["e"]
        np.testing.assert_allclose(
            [r.model_info["ar1_z"], r.model_info["ar2_z"]],
            [e["arm1"], e["arm2"]],
            rtol=1e-7,
            err_msg=f"[{spec}] classical AR z statistics differ from Stata.",
        )

    def test_sargan_onestep(self, abdata, stata):
        """Stata's e(sargan) after one-step non-robust estimation.

        The statistic is ``g' A1 g / sigma2_hat`` with
        ``sigma2_hat = e'e / (2 (N - k))`` — the ``xtabond`` convention.
        (``xtabond2`` divides by ``2N`` instead, so its ``e(sargan)`` sits a
        factor ``N/(N-k)`` higher; that difference is a convention, not an
        error, and is why ``xtabond`` is the anchor here.)
        """
        spec = "A2_ar1_1step_classic"
        r = _fit(abdata, lags=1, twostep=False, robust=False)
        np.testing.assert_allclose(
            r.model_info["sargan_stat"],
            stata[spec]["e"]["sargan"],
            rtol=1e-9,
            err_msg="Sargan statistic differs from Stata's e(sargan).",
        )
        assert r.model_info["sargan_df"] == 27

    def test_hansen_j_matches_stata_twostep_sargan(self, abdata, stata):
        """After ``twostep``, Stata's e(sargan) *is* the Hansen J.

        Stata reuses the ``e(sargan)`` slot for the two-step statistic
        ``g2' A2 g2``, which is the heteroskedasticity-robust Hansen J.
        StatsPAI keeps the two names distinct, so the comparison is against
        ``hansen_stat``.
        """
        spec = "A5_ar1_2step_conv"
        r = _fit(abdata, lags=1, twostep=True, robust=False)
        np.testing.assert_allclose(
            r.model_info["hansen_stat"],
            stata[spec]["e"]["sargan"],
            rtol=1e-9,
            err_msg="Hansen J differs from Stata's post-twostep e(sargan).",
        )
        assert r.model_info["hansen_df"] == 27


# ---------------------------------------------------------------------------
# C. Instrument-window controls: maxldep, deeper minimum lag, collapse.
# ---------------------------------------------------------------------------


class TestInstrumentWindow:
    def test_capped_depth_matches_maxldep(self, abdata, stata):
        """``gmm_lags=(2, 4)`` == Stata ``xtabond ..., maxldep(3)``."""
        spec = "A6_ar1_maxldep3"
        r = _fit(abdata, lags=1, gmm_lags=(2, 4))
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec)

    def test_deeper_minimum_lag(self, abdata, stata):
        """``gmm_lags=(3, None)`` == ``xtabond2 ... gmm(L.n, lag(2 .))``."""
        spec = "A7_minlag3"
        r = _fit(abdata, lags=1, gmm_lags=(3, None))
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec, instrument_key="j")

    def test_collapse_matches_xtabond2(self, abdata, stata):
        """``collapse=True`` == ``xtabond2 ..., gmm(..., collapse)``.

        The whole point of collapsing is that it changes the answer: on
        abdata it moves rho from 1.02 to 1.39 and cuts 28 instruments to 7.
        Matching Stata here is therefore a real test of the collapsed
        moment layout, not of a no-op flag.
        """
        spec = "D2_x2_diff_collapse"
        r = _fit(abdata, lags=1, collapse=True)
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec, instrument_key="j")
        assert r.model_info["n_instruments"] == 7
        assert r.model_info["collapse"] is True


# ---------------------------------------------------------------------------
# D. Lag-operator regressor lists — the Arellano-Bond (1991) Table 4 shape.
#    This is the specification the pre-v1.21 listwise-deletion bug broke.
# ---------------------------------------------------------------------------


class TestLagOperatorSpecifications:
    def test_ab1991_onestep_robust(self, abdata, stata):
        spec = "B1_ab1991_1step_robust"
        r = _fit(abdata, x=["l(0/1).w", "l(0/2).k"], lags=2)
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec)

    def test_ab1991_twostep_windmeijer(self, abdata, stata):
        spec = "B2_ab1991_2step_wc"
        r = _fit(abdata, x=["l(0/1).w", "l(0/2).k"], lags=2, twostep=True)
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec)

    def test_ab1991_with_year_dummies(self, abdata, stata):
        spec = "B3_ab1991_yeardum"
        yrs = [f"yr{t}" for t in range(1979, 1985)]
        r = _fit(abdata, x=["l(0/1).w", "l(0/2).k"] + yrs, lags=2)
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec)

    def test_lag_operator_equals_manual_lags(self, abdata):
        """``l(0/2).k`` must equal hand-built lag columns — now that the
        estimator no longer deletes rows on a covariate's leading NaNs."""
        manual = abdata.sort_values(["id", "year"]).copy()
        for lag in (1, 2):
            manual[f"k_L{lag}"] = manual.groupby("id")["k"].shift(lag)
            manual[f"w_L{lag}"] = manual.groupby("id")["w"].shift(lag)
        a = _fit(abdata, x=["l(0/1).w", "l(0/2).k"], lags=2)
        b = _fit(manual, x=["w", "w_L1", "k", "k_L1", "k_L2"], lags=2)
        np.testing.assert_allclose(
            b.detail["coefficient"].to_numpy(float),
            a.detail["coefficient"].to_numpy(float),
            rtol=1e-10,
            err_msg=(
                "hand-built lag columns disagree with the lag operator — the "
                "listwise-deletion regression is back."
            ),
        )
        assert a.model_info["n_obs"] == b.model_info["n_obs"] == 611
        assert a.model_info["n_instruments"] == b.model_info["n_instruments"] == 32


# ---------------------------------------------------------------------------
# E. Instrument classes: predetermined and endogenous regressors.
#    Pins the documented mapping between StatsPAI's absolute (xtabond2)
#    lag convention and Stata xtabond's "further lags" lagstruct().
# ---------------------------------------------------------------------------


class TestInstrumentClasses:
    def test_predetermined_matches_stata_pre(self, abdata, stata):
        """``pre(w, lagstruct(1, .))`` == ``predetermined_lags=(2, None)``."""
        spec = "C1_w_predetermined"
        r = _fit(
            abdata,
            x=["l(0/2).k"],
            predetermined=["l(0/1).w"],
            predetermined_lags=(2, None),
            lags=2,
        )
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec)

    def test_endogenous_matches_stata_endogenous(self, abdata, stata):
        """``endogenous(w, lagstruct(1, .))`` == ``endogenous_lags=(3, None)``."""
        spec = "C2_w_endogenous"
        r = _fit(
            abdata,
            x=["l(0/2).k"],
            endogenous=["l(0/1).w"],
            endogenous_lags=(3, None),
            lags=2,
        )
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec)

    def test_class_defaults_are_the_xtabond2_convention(self, abdata):
        """Defaults are absolute lags 1+ (predetermined) / 2+ (endogenous).

        Shifting the window one lag deeper must strictly *reduce* the
        instrument count by the number of equation periods that lose their
        shallowest instrument — a structural check that the class default
        really is where the docstring says it is.
        """
        pre_default = _fit(abdata, predetermined=["w"], lags=1)
        pre_shifted = _fit(
            abdata, predetermined=["w"], predetermined_lags=(2, None), lags=1
        )
        endo_default = _fit(abdata, endogenous=["w"], lags=1)
        assert (
            pre_default.model_info["n_instruments"]
            > pre_shifted.model_info["n_instruments"]
        )
        assert (
            pre_shifted.model_info["n_instruments"]
            == endo_default.model_info["n_instruments"]
        ), "endogenous default (lag 2+) must equal predetermined shifted to 2+"


# ---------------------------------------------------------------------------
# F. Cross-software: R plm::pgmm as an independent second anchor.
# ---------------------------------------------------------------------------


@pytest.mark.skipif(not R_JSON.exists(), reason="R fixture not generated")
class TestRParity:
    def test_ab1991_matches_plm_pgmm(self, abdata):
        """plm::pgmm one-step robust on the AB(1991) spec.

        R and Stata are independent implementations; agreeing with both
        rules out a shared-convention coincidence.
        """
        ref = json.loads(R_JSON.read_text(encoding="utf-8"))["R3_ab1991_diff_1step"]
        r = _fit(abdata, x=["l(0/1).w", "l(0/2).k"], lags=2)
        # plm names terms lag(n, 1:2)1, lag(w, 0:1)0, ... in the same order
        # StatsPAI emits them.
        got = r.detail["coefficient"].to_numpy(float)
        want = np.array(list(ref["coef"].values()), dtype=float)
        np.testing.assert_allclose(
            got,
            want,
            rtol=1e-8,
            err_msg="AB(1991) coefficients differ from R plm::pgmm.",
        )

    def test_ar1_matches_pdynmc(self, abdata):
        """pdynmc (a third, independent implementation) on the AR(1) spec."""
        payload = json.loads(R_JSON.read_text(encoding="utf-8"))
        ref = payload.get("R9_pdynmc_ar1_diff_1step")
        if ref is None:
            pytest.skip("pdynmc reference not generated")
        r = _fit(abdata, lags=1)
        np.testing.assert_allclose(
            float(r.detail["coefficient"].iloc[0]),
            float(list(ref["coef"].values())[0]),
            rtol=1e-6,
            err_msg="AR(1) rho differs from R pdynmc.",
        )
        np.testing.assert_allclose(
            float(r.detail["se"].iloc[0]),
            float(list(ref["se"].values())[0]),
            rtol=1e-5,
            err_msg="AR(1) robust SE differs from R pdynmc.",
        )


# ---------------------------------------------------------------------------
# G. Blundell-Bond system GMM against xtabond2.
#
#    xtabond2 is the reference the applied literature reports, so it is the
#    anchor for the whole level-equation layout: which lagged difference
#    instruments the level equation (only the most recent one — deeper lags
#    are redundant given the transformed-equation moments), that iv() enters
#    as a *single* column spanning both equations, that _cons is both a
#    regressor and its own level instrument, and Roodman's h(3) weight
#    H = [[MM', M], [M', I]].
# ---------------------------------------------------------------------------


class TestSystemGMM:
    def test_system_onestep_matches_xtabond2(self, abdata, stata):
        spec = "D4_x2_sys_1step"
        r = _fit(abdata, x=["w", "k"], lags=1, method="system")
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec, instrument_key="j")
        assert r.model_info["n_instruments"] == 38

    def test_system_twostep_windmeijer_matches_xtabond2(self, abdata, stata):
        spec = "D5_x2_sys_2step_wc"
        r = _fit(abdata, x=["w", "k"], lags=1, method="system", twostep=True)
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec, instrument_key="j")

    def test_system_collapsed_matches_xtabond2(self, abdata, stata):
        spec = "D6_x2_sys_collapse"
        r = _fit(
            abdata, x=["w", "k"], lags=1, method="system", twostep=True, collapse=True
        )
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec, instrument_key="j")
        assert r.model_info["n_instruments"] == 11

    def test_system_ar1_matches_xtabond2(self, abdata, stata):
        """The AR test stays a statement about the *differenced* errors.

        Under system GMM only the transformed rows supply residual pairs;
        getting this wrong (letting level rows in) shifts the statistic
        visibly, so matching xtabond2's -2.218 is a real check.
        """
        r = _fit(abdata, x=["w", "k"], lags=1, method="system")
        np.testing.assert_allclose(
            r.model_info["ar1_z"],
            stata["D4_x2_sys_1step"]["e"]["ar1"],
            rtol=1e-7,
            err_msg="system-GMM AR(1) z differs from xtabond2.",
        )

    def test_system_adds_the_level_equation_and_its_moments(self, abdata):
        """Structural check on what stacking the level equation changes.

        Relative to the same difference-GMM fit, system GMM must (a) add
        level rows (891 of them on abdata, one per unit-period with ``n``
        and ``L.n``), (b) add level moments — the 7 lagged-difference
        instruments plus the ``_cons`` column — and (c) report an intercept
        the differenced equation cannot identify. Anything less means the
        level equation was not really stacked.
        """
        diff = _fit(abdata, x=["w", "k"], lags=1)
        system = _fit(abdata, x=["w", "k"], lags=1, method="system")
        assert diff.model_info["n_obs_level"] == 0
        assert system.model_info["n_obs_level"] == 891
        assert system.model_info["n_obs_diff"] == diff.model_info["n_obs_diff"]
        assert system.model_info["n_instruments"] == (
            diff.model_info["n_instruments"] + 8
        )
        assert "_cons" not in list(diff.detail["variable"])
        assert list(system.detail["variable"])[-1] == "_cons"

    def test_xtdpdsys_alias_equals_method_system(self, abdata):
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            a = sp.xtdpdsys(abdata, y="n", x=["w", "k"], id="id", time="year")
        b = _fit(abdata, x=["w", "k"], lags=1, method="system")
        np.testing.assert_allclose(
            a.detail["coefficient"].to_numpy(float),
            b.detail["coefficient"].to_numpy(float),
            rtol=1e-14,
        )

    def test_hansen_j_matches_xtabond2_in_every_configuration(self, abdata, stata):
        """The Hansen J has no free scale, so it must match exactly.

        (The Sargan statistic does have one — see
        ``test_sargan_convention_differs_from_xtabond2`` — which is why the
        J is the cross-package anchor.)
        """
        cases = [
            ("D1_x2_diff_1step", dict(lags=1)),
            ("D2_x2_diff_collapse", dict(lags=1, collapse=True)),
            ("D3_x2_diff_ivwk", dict(x=["w", "k"], lags=1)),
            ("D4_x2_sys_1step", dict(x=["w", "k"], lags=1, method="system")),
            (
                "D6_x2_sys_collapse",
                dict(
                    x=["w", "k"],
                    lags=1,
                    method="system",
                    twostep=True,
                    collapse=True,
                ),
            ),
        ]
        for spec, kwargs in cases:
            r = _fit(abdata, **kwargs)
            np.testing.assert_allclose(
                r.model_info["hansen_stat"],
                stata[spec]["e"]["hansen"],
                rtol=1e-9,
                err_msg=f"[{spec}] Hansen J differs from xtabond2.",
            )
            assert r.model_info["hansen_df"] == int(stata[spec]["e"]["hansen_df"])

    def test_sargan_convention_differs_from_xtabond2_by_a_known_factor(
        self, abdata, stata
    ):
        """Pin the documented scale difference instead of hiding it.

        StatsPAI follows ``xtabond``: ``sigma2 = e*'e* / (2 (N* - k))`` over
        the transformed rows. ``xtabond2`` divides by ``2 N*``. The ratio is
        therefore exactly ``N* / (N* - k)`` — asserting it proves the two are
        the same statistic under two finite-sample conventions, not two
        different statistics.
        """
        for spec, kwargs in (
            ("D1_x2_diff_1step", dict(lags=1)),
            ("D3_x2_diff_ivwk", dict(x=["w", "k"], lags=1)),
            ("D4_x2_sys_1step", dict(x=["w", "k"], lags=1, method="system")),
        ):
            r = _fit(abdata, **kwargs)
            n_star = r.model_info["n_obs_diff"]
            k = r.model_info["n_regressors"]
            np.testing.assert_allclose(
                r.model_info["sargan_stat"] * n_star / (n_star - k),
                stata[spec]["e"]["sargan"],
                rtol=1e-9,
                err_msg=(
                    f"[{spec}] the Sargan statistic no longer differs from "
                    "xtabond2 by exactly N*/(N*-k) — a convention drifted."
                ),
            )


# ---------------------------------------------------------------------------
# H. Forward orthogonal deviations (Arellano-Bover) against
#    ``xtabond2, orthogonal``.
#
#    Two conventions had to be got right and both are observable on this
#    ragged panel:
#      * the transformed row is *labelled* with the period of the first
#        difference it replaces, so the instrument grid, the level-equation
#        cross block and the AR test share one period index;
#      * the a-priori error covariance H is built from the **balanced-grid**
#        FOD operator ("H always has block diagonal form, with all blocks
#        the same" -- xtabond2 help), not from each unit's own operator.
#        Using the per-unit one moves the system-GMM coefficients by up to
#        13% here.
# ---------------------------------------------------------------------------


class TestForwardOrthogonalDeviations:
    def test_fod_difference_onestep(self, abdata, stata):
        spec = "D7_x2_fod_diff"
        r = _fit(abdata, x=["w", "k"], lags=1, orthogonal=True)
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec, instrument_key="j")

    def test_fod_difference_twostep(self, abdata, stata):
        spec = "D10_x2_fod_diff_2step"
        r = _fit(abdata, x=["w", "k"], lags=1, orthogonal=True, twostep=True)
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec, instrument_key="j")

    def test_fod_system_onestep(self, abdata, stata):
        spec = "D9_x2_fod_sys_1step"
        r = _fit(abdata, x=["w", "k"], lags=1, method="system", orthogonal=True)
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec, instrument_key="j")

    def test_fod_system_twostep(self, abdata, stata):
        spec = "D8_x2_fod_sys_2step"
        r = _fit(
            abdata,
            x=["w", "k"],
            lags=1,
            method="system",
            orthogonal=True,
            twostep=True,
        )
        _assert_matches(r, stata[spec], spec)
        _assert_sample(r, stata[spec], spec, instrument_key="j")

    def test_fod_operator_is_orthonormal(self):
        """``M M' = I`` — the property the whole transform exists for.

        It is what makes the transformed errors serially uncorrelated, so
        the one-step weight needs no MA(1) correction. If this breaks, the
        parity above would still pass on abdata but every other panel would
        be silently mis-weighted.
        """
        from statspai.gmm._dynpanel._moments import fod_operator

        for T in (2, 3, 5, 9, 20):
            M = fod_operator(T)
            assert M.shape == (T - 1, T)
            np.testing.assert_allclose(
                M @ M.T, np.eye(T - 1), atol=1e-12, err_msg=f"M M' != I at T={T}"
            )

    def test_fod_beats_first_differences_on_a_gappy_panel(self, abdata):
        """FOD's practical selling point: a gap costs one row, not two.

        Punching an interior hole in every third firm destroys the first
        differences on *both* sides of it, but only one forward deviation.
        The transformed sample must therefore shrink strictly less under
        ``orthogonal=True``.
        """
        holed = abdata[
            ~((abdata["id"] % 3 == 0) & (abdata["year"] == 1980))
        ].reset_index(drop=True)
        fd = _fit(holed, x=["w", "k"], lags=1)
        fod = _fit(holed, x=["w", "k"], lags=1, orthogonal=True)
        full_fd = _fit(abdata, x=["w", "k"], lags=1)
        lost_fd = full_fd.model_info["n_obs_diff"] - fd.model_info["n_obs_diff"]
        lost_fod = (
            _fit(abdata, x=["w", "k"], lags=1, orthogonal=True).model_info["n_obs_diff"]
            - fod.model_info["n_obs_diff"]
        )
        assert lost_fod < lost_fd, (
            f"forward orthogonal deviations lost {lost_fod} rows to the gaps "
            f"and first differencing lost {lost_fd}: FOD is supposed to lose "
            "strictly fewer."
        )


# ---------------------------------------------------------------------------
# I. Gapped panels: exactly where StatsPAI and Stata part company.
# ---------------------------------------------------------------------------


class TestGappedPanelConvention:
    """Localise the known gapped-panel divergence instead of hand-waving it.

    Reference values come from Stata 18 run on the same hole-punched CSV
    (every third firm loses 1980):

        xtabond2 n L.n, gmm(L.n, lag(1 1) collapse) noleveleq noconstant robust
            -> 1.35725540013219      (just identified, N=613, j=1)
        xtabond  n, lags(1) noconstant vce(robust)
            -> 0.908863550951649     (over-identified, N=613, zrank=28)

    The first is reproduced to 2e-15 and the second is not, which is the
    whole point: with one instrument the weight matrix cancels out of the
    estimator, so agreement there proves the *design* — equations, sample,
    instruments — is identical, and pins the disagreement squarely on the
    a-priori covariance ``H``. StatsPAI uses ``H = M M'`` for the actual
    differencing operator; Stata's gapped convention is different and
    undocumented. Both stay consistent; only efficiency differs.
    """

    HOLE_YEAR = 1980

    @pytest.fixture(scope="class")
    def gapped(self, abdata):
        return abdata[
            ~((abdata["id"] % 3 == 0) & (abdata["year"] == self.HOLE_YEAR))
        ].reset_index(drop=True)

    def test_design_matches_stata_exactly(self, gapped):
        """Just-identified fit: no weight matrix, so only the design matters."""
        r = _fit(gapped, lags=1, gmm_lags=(2, 2), collapse=True)
        assert r.model_info["n_instruments"] == 1
        assert r.model_info["n_obs"] == 613
        np.testing.assert_allclose(
            float(r.detail["coefficient"].iloc[0]),
            1.35725540013219,
            rtol=1e-12,
            err_msg=(
                "the just-identified gapped estimate no longer matches Stata — "
                "this one does not involve H at all, so the equation set, the "
                "sample or the instrument itself has drifted."
            ),
        )

    def test_sample_and_instrument_count_still_match_when_overidentified(self, gapped):
        r = _fit(gapped, lags=1)
        assert r.model_info["n_obs"] == 613, "gapped sample size drifted from Stata"
        assert r.model_info["n_instruments"] == 28, "gapped instrument count drifted"

    def test_overidentified_gap_divergence_stays_bounded(self, gapped):
        """The H-convention gap is a known ~4%, not an open-ended drift."""
        r = _fit(gapped, lags=1)
        got = float(r.detail["coefficient"].iloc[0])
        rel = abs(got - 0.908863550951649) / 0.908863550951649
        assert rel < 0.06, (
            f"divergence from Stata on a gapped panel grew to {rel:.1%}; it was "
            "characterised at ~4% and is supposed to come only from the "
            "one-step weight matrix."
        )

    def test_gap_warning_fires_and_is_recorded(self, gapped):
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            r = sp.xtabond(gapped, y="n", id="id", time="year", lags=1)
        messages = [str(w.message) for w in caught]
        assert any(
            "internal time gaps" in m for m in messages
        ), f"no gap warning was emitted; got {messages}"
        assert "gap_warning" in r.model_info, (
            "the caveat must also reach model_info — an agent reading the "
            "result object should see what a human reads on the console."
        )

    def test_no_gap_warning_on_the_intact_panel(self, abdata):
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            r = sp.xtabond(abdata, y="n", id="id", time="year", lags=1)
        assert not any("internal time gaps" in str(w.message) for w in caught)
        assert "gap_warning" not in r.model_info


# ---------------------------------------------------------------------------
# J. Difference-in-Hansen (C) tests of instrument subsets.
# ---------------------------------------------------------------------------


class TestDifferenceInHansen:
    """System GMM's extra level moments, tested rather than assumed.

    Reference: the ``xtabond2`` output block for
    ``xtabond2 n L.n w k, gmm(L.n, lag(1 .)) iv(w k) robust``::

        GMM instruments for levels
          Hansen test excluding group:     chi2(27)   =  56.15
          Difference (null H = exogenous): chi2(7)    =   5.32   p = 0.621
        iv(w k)
          Hansen test excluding group:     chi2(32)   =  58.48
          Difference (null H = exogenous): chi2(2)    =   2.98   p = 0.225

    ``xtabond2`` does not store these in ``e()``, so the reference is the
    printed output and the tolerance is its two-decimal resolution
    (``atol=0.005``). The statistics themselves agree to five decimals
    (56.15056, 5.31583, 58.48238, 2.98401) — the looseness is Stata's
    display, not the estimator's.
    """

    @pytest.fixture(scope="class")
    def system_fit(self, abdata):
        return _fit(abdata, x=["w", "k"], lags=1, method="system")

    def test_level_instrument_group_matches_xtabond2(self, system_fit):
        c = system_fit.model_info["difference_in_hansen"]["GMM instruments for levels"]
        assert c["df"] == 7
        assert c["df_excluding"] == 27
        assert c["hansen_excluding"] == pytest.approx(56.15, abs=0.005)
        assert c["statistic"] == pytest.approx(5.32, abs=0.005)
        assert c["pvalue"] == pytest.approx(0.621, abs=0.001)

    def test_iv_group_matches_xtabond2(self, system_fit):
        groups = system_fit.model_info["difference_in_hansen"]
        key = next(k for k in groups if k.startswith("iv("))
        c = groups[key]
        assert c["df"] == 2
        assert c["df_excluding"] == 32
        assert c["hansen_excluding"] == pytest.approx(58.48, abs=0.005)
        assert c["statistic"] == pytest.approx(2.98, abs=0.005)
        assert c["pvalue"] == pytest.approx(0.225, abs=0.001)

    def test_c_statistic_is_a_genuine_difference(self, system_fit):
        """``C = J_full − J_excluding`` and both pieces are non-negative.

        The identity is what makes the test interpretable; it only holds
        because the restricted fit reuses the full model's moment
        covariance. Re-estimating Omega on the reduced instrument set breaks
        it — and on this very fit flips the level-instrument verdict from
        p = 0.62 to p = 0.009.
        """
        j_full = system_fit.model_info["hansen_stat"]
        for name, c in system_fit.model_info["difference_in_hansen"].items():
            if not np.isfinite(c["hansen_excluding"]):
                continue
            assert c["hansen_excluding"] >= 0, f"[{name}] negative excluded J"
            assert c["statistic"] == pytest.approx(
                j_full - c["hansen_excluding"], rel=1e-10
            ), f"[{name}] C is not J_full - J_excluding"

    def test_difference_gmm_has_no_level_instrument_group(self, abdata):
        """Nothing to test when there are no level moments."""
        r = _fit(abdata, x=["w", "k"], lags=1)
        assert "GMM instruments for levels" not in r.model_info["difference_in_hansen"]

    def test_degrees_of_freedom_add_up(self, system_fit):
        """df(excluding) + df(subset) == df(full Hansen), per subset."""
        full_df = system_fit.model_info["hansen_df"]
        for name, c in system_fit.model_info["difference_in_hansen"].items():
            if not np.isfinite(c["hansen_excluding"]):
                continue
            assert (
                c["df_excluding"] + c["df"] == full_df
            ), f"[{name}] {c['df_excluding']} + {c['df']} != {full_df}"


# ---------------------------------------------------------------------------
# K. Arellano-Bond serial-correlation tests across the full VCE menu.
#
#    The AR variance carries a (W'q)' Avar(beta) (W'q) term.  Evaluating it
#    at the uncorrected robust sandwich — while the coefficient table reports
#    a Windmeijer-corrected or conventional two-step VCE — makes the test
#    disagree with the estimate it is testing.  On the AB(1991) spec that was
#    a 39% error in the AR(1) z (-4.32 against Stata's -3.10).
# ---------------------------------------------------------------------------


class TestArellanoBondSerialCorrelation:
    # e(arm1)/e(arm2) are Stata scalars; xtabond2 stores them as e(ar1)/e(ar2).
    CASES = [
        ("A1_ar1_1step_robust", dict(lags=1), "arm"),
        ("A2_ar1_1step_classic", dict(lags=1, robust=False), "arm"),
        ("A3_ar2_1step_robust", dict(lags=2), "arm"),
        ("A4_ar1_2step_wc", dict(lags=1, twostep=True), "arm"),
        ("A5_ar1_2step_conv", dict(lags=1, twostep=True, robust=False), "arm"),
        ("B1_ab1991_1step_robust", dict(x=["l(0/1).w", "l(0/2).k"], lags=2), "arm"),
        (
            "B2_ab1991_2step_wc",
            dict(x=["l(0/1).w", "l(0/2).k"], lags=2, twostep=True),
            "arm",
        ),
        ("D4_x2_sys_1step", dict(x=["w", "k"], lags=1, method="system"), "ar"),
        (
            "D5_x2_sys_2step_wc",
            dict(x=["w", "k"], lags=1, method="system", twostep=True),
            "ar",
        ),
    ]

    @pytest.mark.parametrize("spec,kwargs,prefix", CASES, ids=[c[0] for c in CASES])
    def test_ar_statistics_match_stata(self, abdata, stata, spec, kwargs, prefix):
        r = _fit(abdata, **kwargs)
        e = stata[spec]["e"]
        for order, key in ((1, f"{prefix}1"), (2, f"{prefix}2")):
            if key not in e:
                continue
            np.testing.assert_allclose(
                r.model_info[f"ar{order}_z"],
                e[key],
                rtol=1e-9,
                err_msg=(
                    f"[{spec}] AR({order}) z differs from Stata — the "
                    "coefficient-variance term in the AR variance no longer "
                    "matches the reported VCE."
                ),
            )

    def test_correction_is_a_no_op_for_onestep_robust(self, abdata):
        """Where the reported and naive VCEs coincide, nothing may change.

        One-step robust reports exactly the sandwich the AR variance
        expansion already uses, so the swap must be identically zero — a
        guard that the correction is targeted rather than a global fudge.
        """
        from statspai.gmm._dynpanel import fit_dynamic_panel
        from statspai.gmm._dynpanel._diagnostics import arellano_bond_ar_test
        from statspai.gmm._dynpanel._estimate import (
            gmm_solve,
            moment_covariance,
            onestep_weight,
        )
        from statspai.gmm._dynpanel._inference import robust_sandwich

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            fit = fit_dynamic_panel(abdata, y="n", id="id", time="year", lags=1)
        design = fit["design"]
        W, Z, dy = design.W, design.Z, design.dy
        A1 = onestep_weight(design)
        beta, Minv, WZ = gmm_solve(W, Z, dy, A1)
        resid = dy - W @ beta
        vcov = robust_sandwich(
            Minv, WZ, A1, moment_covariance(Z, resid, design.unit_rows)
        )
        common = dict(
            unit_rows=design.unit_rows,
            periods=design.row_period,
            order=1,
            Z=Z,
            W=W,
            weight=A1,
            Minv=Minv,
            robust=True,
            sigma2=fit["sigma2"],
            eq_mask=design.row_eq == 0,
        )
        without = arellano_bond_ar_test(resid, **common)
        with_swap = arellano_bond_ar_test(
            resid, coef_vcov=vcov, naive_vcov=vcov, **common
        )
        assert with_swap["z"] == pytest.approx(without["z"], rel=1e-14)

    def test_correction_actually_moves_the_twostep_statistic(self, abdata, stata):
        """Guard against the swap silently becoming a no-op everywhere.

        Two-step Windmeijer on the AB(1991) spec is where it matters most:
        the uncorrected statistic is -4.32, Stata's is -3.10. Assert both
        that we hit Stata and that the two differ by a wide margin, so a
        regression to the old behaviour cannot pass.
        """
        r = _fit(abdata, x=["l(0/1).w", "l(0/2).k"], lags=2, twostep=True)
        got = r.model_info["ar1_z"]
        np.testing.assert_allclose(
            got, stata["B2_ab1991_2step_wc"]["e"]["arm1"], rtol=1e-9
        )
        assert abs(got - (-4.322919)) > 1.0, (
            "the two-step AR statistic fell back to the uncorrected value "
            f"(-4.32); got {got:.4f}."
        )
