"""``sp.etwfe(family='poisson', fe='cohort', xvar=...)`` against R ``etwfe``.

Reference: R 4.5.2, ``etwfe`` 0.6.2 / ``fixest`` 0.14.0 /
``marginaleffects`` 0.32.0 on ``_fixtures/etwfe_poisson_jwdid_hettype.csv``,
generated by ``_fixtures/_generate_etwfe_poisson_xvar_R.R``.

``fe='cohort'`` is R etwfe's design: cohort and period effects, the
covariate demeaned within cohort x period cells, interacted with every
treatment cell (``.Dtreat:i(g, i.year) / x_dm``) and with the periods
(``i(year, x_dm)``).

* **Continuous covariate** (``xc``): the same design on both sides.  Point
  estimates (``emfx`` simple and event, both scales) agree to ~1e-8, the
  clustered SEs to ~1e-4 relative -- fixest's and statsmodels'
  small-sample corrections, as in ``test_etwfe_glm_parity.py``.
* **Categorical covariate** (``xcat``, three levels): ``etwfe`` 0.6.2 writes
  the period term as ``i(year, (xcat2_dm + xcat3_dm))``, which fixest reads
  as one covariate -- the sum of the level dummies -- so the levels share a
  single period slope while the cell interactions are per level.  StatsPAI
  keeps one period slope per level.  That is a reference-implementation
  difference (T4), so the independent evidence is the same design with
  ``i(year, xcat2_dm) + i(year, xcat3_dm)`` fitted by ``fixest::feglm``
  directly and aggregated from counterfactual predictions
  (``.Dtreat = FALSE``) in R: point estimates, overall and per level, agree
  to ~1e-8 (not yet treated) and ~1e-11 (never treated).  A final test pins
  that ``etwfe``'s own summed-slope numbers differ, so a fix upstream is
  noticed.
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import pandas as pd
import pytest

import statspai as sp

_FIX = Path(__file__).resolve().parent / "_fixtures"


@pytest.fixture(scope="module")
def ref():
    return json.loads((_FIX / "etwfe_poisson_xvar_R.json").read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def panel():
    df = pd.read_csv(_FIX / "etwfe_poisson_jwdid_hettype.csv")
    df["xcat"] = df["xcat"].astype("category")
    return df


def _fit(df, **kw):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return sp.etwfe(
            df,
            y="y",
            group="id",
            time="year",
            first_treat="g",
            family="poisson",
            **kw,
        )


def test_continuous_xvar_matches_etwfe(ref, panel):
    R = ref["xc"]
    agg = _fit(panel, xvar="xc").model_info["aggregations"]
    for sc in ("response", "link"):
        s = agg[sc]["simple"]
        assert s["att"] == pytest.approx(R[f"simple_{sc}"]["estimate"], abs=1e-7)
        assert s["se"] == pytest.approx(R[f"simple_{sc}"]["std.error"], rel=3e-4)
        ev = agg[sc]["event"].set_index("relative_time")
        e = R[f"event_{sc}"]
        for t, b, se in zip(e["event"], e["estimate"], e["std.error"]):
            assert ev.loc[t, "att"] == pytest.approx(b, abs=1e-7)
            assert ev.loc[t, "se"] == pytest.approx(se, rel=3e-4)


@pytest.mark.parametrize(
    "name, kw",
    [("xcat_perlevel", {}), ("xcat_never_perlevel", {"cgroup": "nevertreated"})],
)
def test_categorical_xvar_matches_per_level_design(ref, panel, name, kw):
    R = ref[name]
    agg = _fit(panel, xvar="xcat", **kw).model_info["aggregations"]
    for sc in ("link", "response"):
        assert agg[sc]["simple"]["att"] == pytest.approx(R[f"simple_{sc}"], abs=5e-8)
        by = agg[sc]["by_xvar"]
        for lev, b in zip(R["by"], R[f"by_{sc}"]):
            assert by[int(lev)]["simple"]["att"] == pytest.approx(b, abs=5e-8)


def test_etwfe_summed_slope_differs(ref, panel):
    """etwfe 0.6.2's shared period slope for a factor xvar is a different
    model; if a future etwfe fixes it, this will start to fail."""
    R = ref["xcat"]
    got = _fit(panel, xvar="xcat").model_info["aggregations"]["link"]["simple"]
    assert abs(got["att"] - R["simple_link"]["estimate"]) > 1e-3
