"""Weighted Callaway-Sant'Anna parity against R ``did`` 2.3.0.

R ``did::att_gt`` has supported ``weightsname=`` for years; StatsPAI's
``callaway_santanna`` did not, and ``sp.did(..., weights=)`` silently
dropped the argument on the staggered paths. Unit weights are part of
the *estimand* — Baker et al. (2026, §3.1) — so a dropped ω answers a
different question, not a slightly less precise version of the same one.

This module pins the weighted path against the reference implementation
on identical bytes.

Reference generated by ``_generate_cs_weighted_R.R``::

    att_gt(yname="y", tname="t", idname="i", gname="g", xformla = ~ x1,
           weightsname = "w", est_method = <dr|reg|ipw>,
           control_group = <nevertreated|notyettreated>,
           bstrap = FALSE, cband = FALSE, base_period = "universal")
    aggte(., type = <simple|dynamic|group>, bstrap = FALSE, cband = FALSE)

R 4.x, ``did`` 2.3.0.

The panel is engineered so ω matters: a quarter of units carry 20x the
weight and a +4 effect, the rest -1. The unweighted ATT is ~ +0.32 and
the ω-weighted ATT is ~ +3.37 — an order of magnitude apart, so a
silently-dropped weight cannot pass by coincidence.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

import statspai as sp

_FIXTURES = Path(__file__).parent / "_fixtures"
_PANEL = _FIXTURES / "cs_weighted_panel.csv"
_REFERENCE = _FIXTURES / "cs_weighted_reference.csv"

# Nuisance estimation runs through a logit (weighted MLE under ω) and a
# WLS outcome model, so agreement is limited by the two solvers'
# convergence tolerances rather than by the estimator algebra. The
# observed worst case across all 36 cells is 1.6e-11.
_RTOL = 1e-8

# Standard errors are pinned per estimator, because the three differ in
# how completely StatsPAI reproduces DRDID's influence function:
#
#   reg  — exact. The delta-method term for the control regression is
#          implemented, so this matches to machine precision.
#   ipw  — exact as of the influence-function fix in this change set
#          (arm-specific centring + propensity-score estimation effect).
#          Before the fix this path was 9-89% off.
#   dr   — within 1%. The arm centring is now DRDID's, but the nuisance
#          *estimation* effects (``inf.treat.2``, ``inf.cont.2``,
#          ``inf.cont.3``) are not yet propagated. DR is
#          Neyman-orthogonal so these are second-order, which is why the
#          residual is small; it is a known gap, pinned here so it
#          cannot silently grow.
_SE_RTOL = {"reg": 1e-10, "ipw": 1e-6, "dr": 1.0e-2}


@pytest.fixture(scope="module")
def panel() -> pd.DataFrame:
    return pd.read_csv(_PANEL, encoding="utf-8")


@pytest.fixture(scope="module")
def reference() -> pd.DataFrame:
    return pd.read_csv(_REFERENCE, encoding="utf-8")


def _cases():
    ref = pd.read_csv(_REFERENCE, encoding="utf-8")
    for _, row in ref.iterrows():
        for agg in ("simple", "dynamic", "group"):
            yield pytest.param(
                row["est"],
                row["control_group"],
                bool(row["weighted"]),
                agg,
                float(row[f"{agg}_att"]),
                float(row[f"{agg}_se"]),
                id=(
                    f"{row['est']}-{row['control_group']}"
                    f"-{'w' if row['weighted'] else 'unw'}-{agg}"
                ),
            )


@pytest.mark.parametrize("est,control_group,weighted,agg,r_att,r_se", list(_cases()))
def test_weighted_cs_matches_r_did(
    panel, est, control_group, weighted, agg, r_att, r_se
):
    fit = sp.callaway_santanna(
        panel,
        y="y",
        g="g",
        t="t",
        i="i",
        x=["x1"],
        weights="w" if weighted else None,
        estimator=est,
        control_group=control_group,
        base_period="universal",
    )
    out = sp.aggte(fit, type=agg, bstrap=False, cband=False)
    assert out.estimate == pytest.approx(r_att, rel=_RTOL)


@pytest.mark.parametrize("est,control_group,weighted,agg,r_att,r_se", list(_cases()))
def test_weighted_cs_se_matches_r_did(
    panel, est, control_group, weighted, agg, r_att, r_se
):
    """The influence functions must carry ω too, not just the point estimate.

    A weighted point estimate paired with an unweighted SE is the more
    insidious bug: the number moves, so the change looks applied, but the
    confidence interval is for a different estimator.
    """
    fit = sp.callaway_santanna(
        panel,
        y="y",
        g="g",
        t="t",
        i="i",
        x=["x1"],
        weights="w" if weighted else None,
        estimator=est,
        control_group=control_group,
        base_period="universal",
    )
    out = sp.aggte(fit, type=agg, bstrap=False, cband=False)
    assert out.se == pytest.approx(r_se, rel=_SE_RTOL[est])


def test_weighting_actually_moves_the_estimate(panel, reference):
    """Guard against a future regression that re-drops ω silently.

    If ``weights=`` ever stops being honoured, the weighted and
    unweighted rows collapse onto each other and every parity assertion
    above would still pass for the unweighted half. This asserts the gap.
    """
    unw = reference[~reference["weighted"].astype(bool)]["simple_att"]
    wtd = reference[reference["weighted"].astype(bool)]["simple_att"]
    assert unw.max() < 1.0 < wtd.min(), "fixture no longer separates the two"

    a = sp.callaway_santanna(panel, y="y", g="g", t="t", i="i", x=["x1"])
    b = sp.callaway_santanna(panel, y="y", g="g", t="t", i="i", x=["x1"], weights="w")
    assert abs(b.estimate - a.estimate) > 1.0
