#!/usr/bin/env python3
"""Generate ``docs/capabilities.md`` from signatures and registry metadata.

The 2026-09 applied-econometrics review found capability prose that lagged
the code in both directions (options described as missing after they
shipped, limits described more broadly than they are). This table is
derived, not written: every cell comes from ``inspect.signature``, the
registry (``stability``, ``validation_status``, ``limitations``) or the
configuration-level evidence map (``sp.validation_scope``).

Usage::

    python scripts/build_capability_table.py          # rewrite the page
    python scripts/build_capability_table.py --check  # exit 1 on drift
"""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "capabilities.md"

#: (section, function) -- the flagship estimators of the six core workflows.
FLAGSHIP = [
    ("Linear / GLM", "regress"),
    ("Linear / GLM", "logit"),
    ("Linear / GLM", "probit"),
    ("Linear / GLM", "poisson"),
    ("Linear / GLM", "nbreg"),
    ("Linear / GLM", "glm"),
    ("Panel / HDFE", "feols"),
    ("Panel / HDFE", "hdfe_ols"),
    ("Panel / HDFE", "panel"),
    ("Panel / HDFE", "fepois"),
    ("IV", "iv"),
    ("IV", "liml"),
    ("DiD / event study", "did"),
    ("DiD / event study", "callaway_santanna"),
    ("DiD / event study", "sun_abraham"),
    ("DiD / event study", "did_imputation"),
    ("DiD / event study", "etwfe"),
    ("DiD / event study", "did_multiplegt_dyn"),
    ("DiD / event study", "honest_did"),
    ("RD", "rdrobust"),
    ("RD", "rddensity"),
    ("Synthetic control", "synth"),
    ("Synthetic control", "sdid"),
    ("Selection on observables / DML", "psm"),
    ("Selection on observables / DML", "match"),
    ("Selection on observables / DML", "ipw"),
    ("Selection on observables / DML", "aipw"),
    ("Selection on observables / DML", "tmle"),
    ("Selection on observables / DML", "dml"),
    ("Selection on observables / DML", "causal_forest"),
    ("Survey / MI", "svymean"),
    ("Survey / MI", "svyglm"),
    ("Survey / MI", "mice"),
    ("Postestimation", "margins"),
    ("Postestimation", "margins_at"),
    ("Postestimation", "contrast"),
]

_WEIGHT = ("weights", "weight", "sample_weight", "sampling_weights")
_CLUSTER = ("cluster", "clustervars", "cluster_var", "clusters")
_VCE = ("vce", "vcov", "robust", "se_type", "se_method", "variance")


def _params(fn: Any) -> Dict[str, inspect.Parameter]:
    try:
        return dict(inspect.signature(inspect.unwrap(fn)).parameters)
    except (TypeError, ValueError):
        return {}


def _var_kw(params: Dict[str, inspect.Parameter]) -> bool:
    return any(p.kind is inspect.Parameter.VAR_KEYWORD for p in params.values())


def _has(params: Dict[str, Any], names: tuple) -> str:
    hit = [n for n in names if n in params]
    if hit:
        return "`" + "`, `".join(hit) + "`"
    # A dispatcher that forwards **kwargs: the signature cannot say.
    return "via `**kwargs`" if _var_kw(params) else "—"


def _vce_cell(params: Dict[str, inspect.Parameter]) -> str:
    out = []
    for n in _VCE:
        p = params.get(n)
        if p is None:
            continue
        default = p.default
        if default is inspect.Parameter.empty:
            out.append(f"`{n}`")
        else:
            out.append(f"`{n}={default!r}`")
    if out:
        return ", ".join(out)
    return "via `**kwargs`" if _var_kw(params) else "—"


def _backend_cell(params: Dict[str, inspect.Parameter], name: str) -> str:
    if name in ("feols", "fepois"):
        return "pyfixest (varying slopes: native)" if name == "feols" else "pyfixest"
    p = params.get("backend")
    if p is not None and p.default is not inspect.Parameter.empty:
        return f"native (`backend={p.default!r}`)"
    return "native"


def build() -> str:
    sys.path.insert(0, str(ROOT / "src"))
    import statspai as sp
    from statspai.registry import describe_function
    from statspai.validation_scope import SCOPES

    lines: List[str] = [
        "# Capability table",
        "",
        "<!-- Generated by scripts/build_capability_table.py -- do not edit. -->",
        "",
        "Options and evidence for the flagship estimators, read from their "
        "signatures and the registry. **Evidence tier** is the function-level "
        "summary (`sp.describe_function(name)['validation_status']`); "
        "**config map** says whether `sp.validation_scope` can tell you which "
        "*configurations and outputs* of a fit were actually compared. A tier "
        "never covers options that no evidence row ran -- check the map (or "
        "`sp.result_card(fit)['evidence']`) for the call you made. **Support "
        "tier** (`sp.support_tier(name)`) is derived: *core* = stable with "
        "numerical evidence, *extension* = stable and contract-tested without "
        "it, *research* = experimental or heuristic (LLM / neural).",
        "",
    ]
    sections: Dict[str, List[str]] = {}
    for sec, name in FLAGSHIP:
        sections.setdefault(sec, []).append(name)
    for sec, names in sections.items():
        lines += [
            f"## {sec}",
            "",
            "| function | weights | clustering | variance options | backend "
            "| support tier | evidence tier | config map | limitations |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
        for name in names:
            fn = getattr(sp, name, None)
            if fn is None:
                raise SystemExit(f"flagship function sp.{name} does not exist")
            params = _params(fn)
            try:
                d = describe_function(name)
            except (KeyError, ValueError):
                d = {}
            n_lim = len(d.get("limitations") or [])
            lines.append(
                f"| `sp.{name}` | {_has(params, _WEIGHT)} "
                f"| {_has(params, _CLUSTER)} | {_vce_cell(params)} "
                f"| {_backend_cell(params, name)} | {d.get('support_tier', '?')} "
                f"| {d.get('validation_status', '?')} "
                f"| {'yes' if name in SCOPES else '—'} | {n_lim if n_lim else '—'} |"
            )
        lines.append("")
    lines += [
        "Limitations are listed in full by `sp.describe_function(name)"
        "['limitations']` and in every MCP tool description.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = build()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(
                "docs/capabilities.md is stale; run "
                "python scripts/build_capability_table.py",
                file=sys.stderr,
            )
            return 1
        print("docs/capabilities.md OK")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
